"""Specialized capability packs built on the universal SolutionGraph core."""

from solutiongraph.specialized.assets import (
    SpecializedAssetInventory,
    reference_specialized_asset_inventory,
    validate_specialized_pack_assets,
    validate_specialized_pack_catalog,
)
from solutiongraph.specialized.builtins import (
    DATA_ANALYSIS_PACK,
    DATA_ENGINEERING_PACK,
    DATA_SCIENCE_PACK,
    LLM_ENGINEERING_PACK,
    ML_ENGINEERING_PACK,
    OPERATIONS_PACK,
    REFERENCE_SPECIALIZED_PACK_REGISTRY,
    REFERENCE_SPECIALIZED_PACKS,
    SOFTWARE_ENGINEERING_PACK,
    SPECIALIZED_PACK_BY_ID,
)
from solutiongraph.specialized.composition import (
    CompositionCandidate,
    CompositionStep,
    PackageCompositionReport,
    PackageCompositionRequest,
    compose_specialized_packs,
)
from solutiongraph.specialized.discovery import (
    PackProviderLoadResult,
    PackProviderReference,
    discover_installed_pack_providers,
    load_and_merge_installed_pack_providers,
    load_installed_pack_provider,
    load_installed_pack_providers,
    merge_specialized_packs,
)
from solutiongraph.specialized.model import (
    GATE_DECISIONS,
    METRIC_DIRECTIONS,
    ORACLE_KINDS,
    PACK_READINESS,
    PROFILE_MODES,
    PROFILE_VALUE_KINDS,
    SPECIALIZED_PACK_ENTRY_POINT_GROUP,
    SPECIALIZED_PACK_MODEL_VERSION,
    EvaluationMetric,
    PackRecipe,
    ProfilerFeature,
    QualityGate,
    SpecializedPackDefinition,
    SpecializedPackRegistry,
)
from solutiongraph.specialized.recommendation import (
    PackageRecommendationReport,
    PackRecommendation,
    TaskPackageRequest,
    recommend_specialized_packs,
    request_from_task_contract,
)

__all__ = [
    "DATA_ANALYSIS_PACK",
    "DATA_ENGINEERING_PACK",
    "DATA_SCIENCE_PACK",
    "GATE_DECISIONS",
    "LLM_ENGINEERING_PACK",
    "METRIC_DIRECTIONS",
    "ML_ENGINEERING_PACK",
    "OPERATIONS_PACK",
    "ORACLE_KINDS",
    "PACK_READINESS",
    "PROFILE_MODES",
    "PROFILE_VALUE_KINDS",
    "REFERENCE_SPECIALIZED_PACK_REGISTRY",
    "REFERENCE_SPECIALIZED_PACKS",
    "SOFTWARE_ENGINEERING_PACK",
    "SPECIALIZED_PACK_BY_ID",
    "SPECIALIZED_PACK_ENTRY_POINT_GROUP",
    "SPECIALIZED_PACK_MODEL_VERSION",
    "CompositionCandidate",
    "CompositionStep",
    "EvaluationMetric",
    "PackProviderLoadResult",
    "PackProviderReference",
    "PackRecipe",
    "PackRecommendation",
    "PackageCompositionReport",
    "PackageCompositionRequest",
    "PackageRecommendationReport",
    "ProfilerFeature",
    "QualityGate",
    "SpecializedAssetInventory",
    "SpecializedPackDefinition",
    "SpecializedPackRegistry",
    "TaskPackageRequest",
    "compose_specialized_packs",
    "discover_installed_pack_providers",
    "load_and_merge_installed_pack_providers",
    "load_installed_pack_provider",
    "load_installed_pack_providers",
    "merge_specialized_packs",
    "recommend_specialized_packs",
    "reference_specialized_asset_inventory",
    "request_from_task_contract",
    "validate_specialized_pack_assets",
    "validate_specialized_pack_catalog",
]
