"""Specialized capability pack for statistical and predictive data science."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "data-science"

FEATURES = (
    feature(
        NAMESPACE,
        "task-family",
        "Task family",
        "Classify supervised, unsupervised, forecasting, ranking, causal, or numerical outcome semantics.",
        "category",
    ),
    feature(
        NAMESPACE,
        "sample-feature-ratio",
        "Sample-to-feature ratio",
        "Compute effective sample size relative to raw and encoded feature counts.",
        "number",
    ),
    feature(
        NAMESPACE,
        "target-shape",
        "Target shape",
        "Measure balance, skew, tails, modes, censoring, zero inflation, and missing labels.",
        "distribution",
    ),
    feature(
        NAMESPACE,
        "feature-shape-summary",
        "Feature-shape summary",
        "Aggregate cardinality, skew, tail, sparsity, monotonicity, and missingness across features.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "dependence-collinearity",
        "Dependence and collinearity",
        "Summarize linear and nonlinear dependence, redundant groups, and leakage candidates.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "split-risk",
        "Split and leakage risk",
        "Detect entity, group, temporal, spatial, and preprocessing boundaries that can contaminate evaluation.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "outlier-cluster-profile",
        "Outlier and cluster profile",
        "Summarize candidate anomalies, density changes, rare slices, and cluster stability.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "task-data-profile-embedding",
        "Task and data-profile embedding",
        "Optional joint embedding of task semantics and redacted profile statistics for historical route retrieval in an exact space.",
    ),
)

METRICS = (
    metric(
        NAMESPACE,
        "task-quality",
        "Task quality",
        "Primary fixed task metric evaluated on the declared validation or holdout split.",
        "maximize",
        "task-metric",
        scope="scope.holdout",
    ),
    metric(
        NAMESPACE,
        "calibration-error",
        "Calibration error",
        "Error between predicted confidence or interval coverage and observed outcomes.",
        "minimize",
        "ratio",
        scope="scope.holdout",
    ),
    metric(
        NAMESPACE,
        "stability-loss",
        "Stability loss",
        "Quality deterioration across seeds, perturbations, time slices, and protected stress cases.",
        "minimize",
        "task-metric",
        scope="scope.stress",
    ),
    metric(
        NAMESPACE,
        "leakage-violations",
        "Leakage violations",
        "Count of independently detected split, label, future, group, or preprocessing leakage violations.",
        "minimize",
        "count",
        scope="scope.pipeline",
    ),
    metric(
        NAMESPACE,
        "uncertainty-coverage",
        "Uncertainty coverage",
        "Observed coverage of declared prediction sets or intervals.",
        "target",
        "ratio",
        scope="scope.holdout",
    ),
    metric(
        NAMESPACE,
        "model-complexity",
        "Model complexity",
        "Declared complexity or resource proxy retained as a separate Pareto objective.",
        "minimize",
        "resource-unit",
        scope="scope.model",
    ),
)

GATES = (
    gate(
        NAMESPACE,
        "leakage-safe",
        "Leakage-safe evaluation",
        "Reject any route with independently detected leakage or split-identity drift.",
        (METRICS[3].id,),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "holdout-acceptance",
        "Holdout acceptance",
        "Reject promotion unless fixed quality, calibration, stability, and uncertainty contracts pass on untouched evidence.",
        (METRICS[0].id, METRICS[1].id, METRICS[2].id, METRICS[4].id),
        oracle_kind="statistical",
    ),
)

RECIPES = (
    recipe(
        NAMESPACE,
        "supervised-modeling",
        "Leakage-safe supervised modeling",
        "Compare explicit preprocessing, feature, model, calibration, ensemble, and verification candidates for classification or regression.",
        ("artifact.validated-dataset",),
        ("artifact.evaluated-model",),
        ("ml.split", "ml.feature", "ml.fit", "ml.calibrate", "ml.verify"),
        (
            "dag.prepare.split",
            "dag.learn.feature",
            "dag.learn.regression",
            "dag.learn.classification",
            "dag.evaluate.model",
        ),
        ("template.kaggle-tabular",),
        node_packs=(
            "example.data-science-lifecycle-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        question_packs=("question-pack.ml-dataset", "question-pack.generic-tabular"),
        design_packs=(
            "design-pack.validation-splits",
            "design-pack.feature-engineering",
            "design-pack.baselines-models",
            "design-pack.tuning-search",
            "design-pack.evaluation-error",
        ),
        examples=(
            "robust-regression-and-conformal",
            "imbalanced-classification-and-calibration",
            "wide-table-feature-reduction",
        ),
        benchmarks=("benchmark.tabular-regression", "benchmark.tabular-classification"),
        arena_tasks=(
            "arena.robust-regression-and-conformal",
            "arena.imbalanced-classification-and-calibration",
            "arena.wide-table-feature-reduction",
        ),
    ),
    recipe(
        NAMESPACE,
        "enriched-supervised-modeling",
        "Enriched supervised modeling",
        "Preserve enrichment provenance while evaluating predictive features, models, calibration, and error slices.",
        ("artifact.enriched-dataset",),
        ("artifact.evaluated-model",),
        ("ml.split", "ml.feature", "ml.fit", "ml.calibrate", "ml.verify"),
        (
            "dag.prepare.split",
            "dag.learn.feature",
            "dag.learn.regression",
            "dag.learn.classification",
            "dag.evaluate.model",
        ),
        ("template.kaggle-tabular",),
        node_packs=(
            "example.data-science-lifecycle-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        question_packs=("question-pack.ml-dataset",),
        design_packs=(
            "design-pack.validation-splits",
            "design-pack.feature-engineering",
            "design-pack.evaluation-error",
        ),
        examples=("tabular-regression", "tabular-classification"),
        benchmarks=("benchmark.tabular-regression", "benchmark.tabular-classification"),
        arena_tasks=("arena.tabular-prediction",),
    ),
    recipe(
        NAMESPACE,
        "forecasting-backtest",
        "Time-series forecasting and backtest",
        "Freeze horizon and availability, construct rolling splits and temporal features, reconcile forecasts, and verify interval coverage.",
        ("artifact.validated-dataset",),
        ("artifact.forecast",),
        (
            "forecast.split",
            "forecast.feature",
            "forecast.fit",
            "forecast.reconcile",
            "forecast.verify",
        ),
        ("dag.learn.forecast", "dag.learn.uncertainty", "dag.evaluate.model"),
        ("template.time-series-forecasting",),
        node_packs=("example.data-science-lifecycle-node-pack",),
        question_packs=("question-pack.datetime", "question-pack.ml-dataset"),
        design_packs=(
            "design-pack.time-series",
            "design-pack.validation-splits",
            "design-pack.ensemble-calibration",
        ),
        examples=("time-series-feature-backtest", "calibrated-time-series-forecast"),
        arena_tasks=("arena.time-series-feature-backtest", "arena.calibrated-forecast"),
    ),
    recipe(
        NAMESPACE,
        "segmentation-anomaly",
        "Segmentation and anomaly discovery",
        "Compare representation, clustering, anomaly, stability, and explanation routes without manufacturing labels.",
        ("artifact.validated-dataset",),
        ("artifact.segment-model",),
        ("ml.represent", "ml.cluster", "ml.anomaly", "ml.stability", "ml.explain"),
        (
            "dag.learn.embedding",
            "dag.learn.cluster",
            "dag.learn.anomaly",
            "dag.evaluate.metamorphic",
        ),
        ("template.scientific-experiment",),
        node_packs=("example.data-science-lifecycle-node-pack",),
        design_packs=(
            "design-pack.selection-reduction",
            "design-pack.robustness-stability",
            "design-pack.interpretability",
        ),
        examples=("unsupervised-segmentation-and-anomaly",),
        arena_tasks=("arena.unsupervised-segmentation-and-anomaly",),
    ),
    recipe(
        NAMESPACE,
        "ranking-ensemble",
        "Ranking, recommendation, and ensemble selection",
        "Construct eligible candidates, compare ranking/model families, calibrate or ensemble, and evaluate exposure and failure diversity.",
        ("artifact.validated-dataset",),
        ("artifact.evaluated-model",),
        ("ml.candidates", "ml.rank", "ml.ensemble", "ml.calibrate", "ml.verify"),
        ("dag.learn.ranking", "dag.learn.ensemble", "dag.learn.uncertainty", "dag.evaluate.model"),
        ("template.recommendation-ranking",),
        node_packs=("example.extended-arena-node-pack", "example.data-science-lifecycle-node-pack"),
        design_packs=("design-pack.ensemble-calibration", "design-pack.evaluation-error"),
        examples=("recommendation-ranking", "ensemble-selection-and-stacking"),
        arena_tasks=("arena.recommendation-ranking", "arena.ensemble-selection-and-stacking"),
    ),
)

PACK = specialized_pack(
    "data_science",
    "Data science",
    "Leakage-safe regression, classification, forecasting, ranking, clustering, anomaly, uncertainty, and ensemble solution spaces.",
    domain_packs=("domain-pack.ai-ml", "domain-pack.science-optimization"),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "data science",
        "regression",
        "classification",
        "forecasting",
        "time series",
        "clustering",
        "anomaly detection",
        "feature engineering",
        "calibration",
        "conformal",
        "ensemble",
        "kaggle",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)

__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
