"""Specialized capability pack for exploratory and decision-oriented analysis."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "data-analysis"

FEATURES = (
    feature(
        NAMESPACE,
        "distribution-shapes",
        "Distribution shapes",
        "Classify skew, tails, multimodality, discreteness, and zero inflation for candidate measures.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "segment-coverage",
        "Segment coverage",
        "Measure sample size, missingness, and support across declared cohorts and slices.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "temporal-span",
        "Temporal span",
        "Measure observation range, cadence, gaps, seasonality candidates, and censoring boundaries.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "spatial-support",
        "Spatial support",
        "Summarize geographic coverage, resolution, CRS, and boundary uncertainty.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "association-profile",
        "Association profile",
        "Summarize pairwise dependence, nonlinearity, collinearity, and sparse interactions without causal claims.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "question-completeness",
        "Question completeness",
        "Record whether population, unit, measure, time, comparison, and decision are explicit.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "analysis-intent-embedding",
        "Analysis-intent embedding",
        "Optional embedding of the analysis question and evidence contract for historical retrieval in an exact declared space.",
    ),
)

METRICS = (
    metric(
        NAMESPACE,
        "reproducibility",
        "Reproducibility",
        "Share of reported findings reproducible from content-addressed inputs and declared transformations.",
        "maximize",
        "ratio",
        scope="scope.analysis-report",
    ),
    metric(
        NAMESPACE,
        "finding-support",
        "Finding support",
        "Share of findings linked to sufficient observations, uncertainty, and source evidence.",
        "maximize",
        "ratio",
        scope="scope.analysis-report",
    ),
    metric(
        NAMESPACE,
        "slice-coverage",
        "Slice coverage",
        "Share of decision-relevant cohorts receiving minimum-sample diagnostics.",
        "maximize",
        "ratio",
        scope="scope.analysis-report",
    ),
    metric(
        NAMESPACE,
        "false-discovery-risk",
        "False-discovery risk",
        "Multiplicity-adjusted risk assigned by the fixed statistical evaluation plan.",
        "minimize",
        "probability",
        scope="scope.analysis-report",
        evidence=("evidence.statistical-protocol", "evidence.independent-evaluation"),
    ),
    metric(
        NAMESPACE,
        "decision-utility",
        "Decision utility",
        "Observed utility of the analysis for the declared downstream decision under its evaluation protocol.",
        "maximize",
        "domain-unit",
        scope="scope.decision",
    ),
)

GATES = (
    gate(
        NAMESPACE,
        "evidence-traceability",
        "Evidence traceability",
        "Reject a report when material claims cannot be reproduced or traced to sufficient evidence.",
        (METRICS[0].id, METRICS[1].id),
    ),
    gate(
        NAMESPACE,
        "statistical-claims",
        "Statistical claims",
        "Escalate claims whose slice support or fixed multiplicity protocol is insufficient.",
        (METRICS[2].id, METRICS[3].id),
        oracle_kind="statistical",
        decision="escalate",
    ),
)

RECIPES = (
    recipe(
        NAMESPACE,
        "exploratory-analysis",
        "Exploratory analysis and evidence report",
        "Profile distributions, missingness, associations, anomalies, slices, and conflicting findings before producing a reproducible report.",
        ("artifact.validated-dataset",),
        ("artifact.analysis-report",),
        ("analysis.profile", "analysis.explore", "analysis.visualize", "analysis.report"),
        ("dag.prepare.profile", "dag.integrate.aggregate", "dag.generate.report"),
        ("template.scientific-experiment",),
        node_packs=("interrogation.semantic-data-node-pack", "design-atlas.data-science-node-pack"),
        question_packs=("question-pack.generic-tabular", "question-pack.ml-dataset"),
        design_packs=(
            "design-pack.profiling-eda",
            "design-pack.evaluation-error",
            "design-pack.decision-handoff",
        ),
        examples=("dataset-profiling-and-drift", "scientific-experiment"),
        arena_tasks=("arena.dataset-profiling-and-drift", "arena.scientific-experiment"),
    ),
    recipe(
        NAMESPACE,
        "cohort-flow-analysis",
        "Cohort, funnel, and user-flow analysis",
        "Construct identity- and event-time-aware cohorts, paths, funnels, retention measures, and counter-slices with explicit denominators.",
        ("artifact.enriched-dataset",),
        ("artifact.analysis-report",),
        ("analysis.cohort", "analysis.sequence", "analysis.funnel", "analysis.retention"),
        ("dag.integrate.aggregate", "dag.learn.causal", "dag.evaluate.online"),
        ("template.event-driven-system", "template.scientific-experiment"),
        node_packs=("example.engineering-showcase-node-pack",),
        design_packs=("design-pack.time-series", "design-pack.causality-experiments"),
        examples=("user-journey-modeling",),
        arena_tasks=("arena.scientific-experiment",),
    ),
    recipe(
        NAMESPACE,
        "geotemporal-analysis",
        "Geospatial and temporal analysis",
        "Validate spatial and temporal support, construct explicit joins, quantify boundary uncertainty, and report map-ready evidence.",
        ("artifact.enriched-dataset",),
        ("artifact.decision-evidence",),
        ("analysis.spatial", "analysis.temporal", "analysis.geotemporal", "analysis.verify"),
        ("dag.integrate.enrich.geotemporal", "dag.integrate.aggregate", "dag.evaluate.data"),
        ("template.geospatial-analytics", "template.time-series-forecasting"),
        node_packs=("example.engineering-showcase-node-pack",),
        question_packs=("question-pack.geography", "question-pack.datetime"),
        design_packs=("design-pack.geospatial", "design-pack.time-series"),
        examples=("geotemporal-enrichment", "exact-gis-boundary-resolution"),
        arena_tasks=("arena.geospatial-data-product", "arena.exact-gis-boundary-resolution"),
    ),
    recipe(
        NAMESPACE,
        "experiment-analysis",
        "Experiment and causal analysis",
        "Freeze estimand, assignment, exclusions, power, diagnostics, sensitivity, and decision thresholds before interpreting outcomes.",
        ("artifact.validated-dataset",),
        ("artifact.decision-evidence",),
        (
            "analysis.experiment-design",
            "analysis.estimate",
            "analysis.sensitivity",
            "analysis.decide",
        ),
        ("dag.learn.causal", "dag.evaluate.model", "dag.evaluate.online"),
        ("template.scientific-experiment",),
        node_packs=("example.extended-arena-node-pack", "design-atlas.data-science-node-pack"),
        design_packs=(
            "design-pack.causality-experiments",
            "design-pack.robustness-stability",
            "design-pack.decision-handoff",
        ),
        examples=("scientific-experiment",),
        arena_tasks=("arena.scientific-experiment",),
    ),
)

PACK = specialized_pack(
    "data_analysis",
    "Data analysis",
    "Exploratory, cohort, funnel, geotemporal, experiment, and decision-evidence workflows with explicit uncertainty and traceability.",
    domain_packs=("domain-pack.data-integration", "domain-pack.science-optimization"),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "exploratory data analysis",
        "eda",
        "analysis",
        "cohort",
        "funnel",
        "retention",
        "user flow",
        "dashboard",
        "finding",
        "geotemporal analysis",
        "experiment analysis",
        "causal analysis",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)

__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
