"""Specialized capability pack for data engineering and data quality."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "data-engineering"

FEATURES = (
    feature(
        NAMESPACE,
        "row-column-shape",
        "Row and column shape",
        "Count rows, columns, and sparse structural regions.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "null-density",
        "Null density",
        "Measure missingness overall, by field, and by co-missingness pattern.",
        "distribution",
    ),
    feature(
        NAMESPACE,
        "duplicate-density",
        "Duplicate density",
        "Measure exact and candidate-key duplicate rates without merging records.",
        "number",
    ),
    feature(
        NAMESPACE,
        "schema-drift",
        "Schema drift",
        "Compare names, types, cardinalities, and constraints with a declared baseline.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "temporal-coverage",
        "Temporal coverage",
        "Summarize event-time range, gaps, ordering, and timezone evidence.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "geographic-coverage",
        "Geographic coverage",
        "Summarize address, postal, coordinate, CRS, and jurisdiction coverage.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "data-profile-embedding",
        "Data-profile embedding",
        "Optional embedding of a redacted deterministic data profile; the exact vector space must be declared before comparison.",
    ),
)

METRICS = (
    metric(
        NAMESPACE,
        "contract-pass-rate",
        "Contract pass rate",
        "Share of records accepted by the independently identified data contract.",
        "maximize",
        "ratio",
        scope="scope.record-set",
    ),
    metric(
        NAMESPACE,
        "invalid-record-rate",
        "Invalid record rate",
        "Share of records rejected for structural or semantic violations.",
        "minimize",
        "ratio",
        scope="scope.record-set",
    ),
    metric(
        NAMESPACE,
        "unresolved-duplicate-rate",
        "Unresolved duplicate rate",
        "Share of records remaining in unresolved duplicate clusters.",
        "minimize",
        "ratio",
        scope="scope.record-set",
    ),
    metric(
        NAMESPACE,
        "reconciliation-error",
        "Reconciliation error",
        "Absolute discrepancy remaining across declared sources or balances.",
        "minimize",
        "domain-unit",
        scope="scope.dataset",
    ),
    metric(
        NAMESPACE,
        "lineage-coverage",
        "Lineage coverage",
        "Share of published fields bound to source and transformation evidence.",
        "maximize",
        "ratio",
        scope="scope.dataset",
    ),
    metric(
        NAMESPACE,
        "late-event-loss",
        "Late-event loss",
        "Share of admissible late events missing from final materialized results.",
        "minimize",
        "ratio",
        scope="scope.stream",
    ),
)

GATES = (
    gate(
        NAMESPACE,
        "publish-contract",
        "Publication contract",
        "Reject publication when required schema, semantic, reconciliation, or lineage checks fail.",
        tuple(item.id for item in METRICS[:5]),
    ),
    gate(
        NAMESPACE,
        "event-time-integrity",
        "Event-time integrity",
        "Reject a stream materialization when the fixed event-time oracle detects silent admissible-event loss.",
        (METRICS[-1].id,),
        oracle_kind="cross-implementation",
    ),
)

RECIPES = (
    recipe(
        NAMESPACE,
        "batch-quality",
        "Batch quality and contract pipeline",
        "Profile, normalize, validate, repair in shadow, independently verify, and publish records.",
        ("artifact.raw-records",),
        ("artifact.validated-dataset",),
        ("records.profile", "records.normalize", "records.validate", "records.verify"),
        ("dag.acquire.batch", "dag.prepare.profile", "dag.prepare.clean", "dag.prepare.verify"),
        ("template.data-quality", "template.batch-data-pipeline"),
        node_packs=("stdlib.data-foundation-node-pack", "interrogation.semantic-data-node-pack"),
        question_packs=(
            "question-pack.generic-tabular",
            "question-pack.organization",
            "question-pack.postal-address",
        ),
        design_packs=("design-pack.schema-semantics", "design-pack.quality-cleaning"),
        examples=("stdlib-data-quality", "data-cleanup", "conflict-aware-data-contract"),
        benchmarks=("benchmark.stdlib-data-quality", "benchmark.data-cleaning"),
        arena_tasks=("arena.validated-analytical-dataset", "arena.conflict-aware-data-contract"),
    ),
    recipe(
        NAMESPACE,
        "reference-enrichment",
        "Identity, geographic, and temporal enrichment",
        "Resolve entities and join versioned postal, geographic, temporal, and reference evidence with abstention.",
        ("artifact.validated-dataset",),
        ("artifact.enriched-dataset",),
        ("records.entity-resolve", "records.reference-enrich", "records.geotemporal-enrich"),
        (
            "dag.integrate.enrich",
            "dag.integrate.enrich.identity",
            "dag.integrate.enrich.geotemporal",
        ),
        ("template.data-quality", "template.geospatial-analytics"),
        node_packs=(
            "example.real-world-node-pack",
            "example.engineering-showcase-node-pack",
            "interrogation.semantic-data-node-pack",
        ),
        question_packs=(
            "question-pack.organization",
            "question-pack.postal-address",
            "question-pack.datetime",
            "question-pack.geography",
        ),
        design_packs=("design-pack.geospatial", "design-pack.time-series"),
        examples=(
            "golden-customer-table",
            "address-reference-verification",
            "geotemporal-enrichment",
        ),
        arena_tasks=(
            "arena.golden-customer-table",
            "arena.geospatial-enrichment",
            "arena.usps-address-verification",
        ),
        limitations=(
            "Bundled reference tables are teaching fixtures, not authoritative postal, census, or geocoding services.",
        ),
    ),
    recipe(
        NAMESPACE,
        "multi-source-reconciliation",
        "Multi-source merge and reconciliation",
        "Preserve source identities, resolve conflicts, balance facts, and emit an auditable analytical dataset.",
        ("artifact.enriched-dataset",),
        ("artifact.reconciled-dataset",),
        ("records.merge", "records.reconcile", "records.provenance"),
        ("dag.integrate.join", "dag.integrate.reconcile", "dag.prepare.conflict"),
        ("template.batch-data-pipeline",),
        node_packs=("example.real-world-node-pack", "example.extended-arena-node-pack"),
        question_packs=("question-pack.transaction", "question-pack.generic-tabular"),
        design_packs=("design-pack.data-source", "design-pack.reproducibility-governance"),
        examples=("multi-feed-analytical-dataset", "transaction-reconciliation"),
        arena_tasks=("arena.transaction-reconciliation", "arena.validated-analytical-dataset"),
    ),
    recipe(
        NAMESPACE,
        "event-time-materialization",
        "Event-time stream materialization",
        "Decode events, apply explicit windows and lateness policy, reconcile revisions, and publish lineage-aware state.",
        ("artifact.raw-events",),
        ("artifact.validated-dataset",),
        ("events.decode", "events.window", "events.reconcile", "events.observe"),
        ("dag.acquire.stream", "dag.prepare.parse", "dag.integrate.aggregate"),
        ("template.event-driven-system",),
        node_packs=("example.engineering-showcase-node-pack",),
        examples=("event-time-windowing",),
        arena_tasks=("arena.event-time-windowing",),
        adapters=("adapter.cloudevents", "adapter.orchestrator.dagster"),
    ),
)

PACK = specialized_pack(
    "data_engineering",
    "Data engineering",
    "Composable quality, cleaning, contracts, enrichment, entity resolution, reconciliation, batch, and event-time data pipelines.",
    domain_packs=(
        "domain-pack.data-integration",
        "domain-pack.event-stream",
        "domain-pack.database-storage",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "data cleaning",
        "data validation",
        "data quality",
        "etl",
        "elt",
        "schema drift",
        "entity resolution",
        "address",
        "geospatial",
        "gis",
        "event time",
        "reconciliation",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)

__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
