"""Specialized package for grounded document ingestion, extraction, and rendering."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "document-intelligence"
FEATURES = (
    feature(
        NAMESPACE,
        "format-layout",
        "Format and layout",
        "Profile formats, pages, regions, tables, forms, reading order, images, fonts, and render requirements.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "text-quality",
        "Text and OCR quality",
        "Measure native text coverage, OCR need, language, corruption, confidence, and source-span availability.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "schema-grounding",
        "Schema and grounding",
        "Profile requested fields, types, cardinalities, totals, citations, redaction classes, and abstention rules.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "document-embedding",
        "Document profile embedding",
        "Optional redacted document-profile embedding for retrieval under an exact embedding-space identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "field-accuracy",
        "Field accuracy",
        "Independently verified extracted fields by schema and document slice.",
        "maximize",
        "ratio",
        scope="scope.field",
    ),
    metric(
        NAMESPACE,
        "grounding",
        "Source grounding",
        "Material outputs bound to exact source spans, regions, pages, and content digests.",
        "maximize",
        "ratio",
        scope="scope.output",
    ),
    metric(
        NAMESPACE,
        "visual-regression",
        "Visual regression",
        "Unexpected layout, clipping, overflow, font, image, or pagination differences.",
        "minimize",
        "count",
        scope="scope.render",
    ),
    metric(
        NAMESPACE,
        "prohibited-leakage",
        "Prohibited leakage",
        "Residual prohibited content after redaction or governed transformation.",
        "minimize",
        "count",
        scope="scope.document",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "extraction",
        "Grounded extraction gate",
        "Reject structured output that fails schema, reconciliation, or source-grounding requirements.",
        (METRICS[0].id, METRICS[1].id),
        oracle_kind="cross-implementation",
    ),
    gate(
        NAMESPACE,
        "document",
        "Document release gate",
        "Reject rendered or redacted documents with visual regressions or prohibited leakage.",
        (METRICS[2].id, METRICS[3].id),
        oracle_kind="property",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "extract",
        "Grounded document extraction",
        "Detect format, decode text and layout, extract typed fields, reconcile values, ground claims, and verify the schema.",
        ("artifact.document-corpus",),
        ("artifact.structured-dataset",),
        (
            "document.detect",
            "document.decode",
            "document.layout",
            "document.extract",
            "document.ground",
            "document.verify",
        ),
        ("dag.acquire.document", "dag.prepare.parse", "dag.prepare.schema", "dag.prepare.verify"),
        ("template.document-intelligence",),
        node_packs=("example.real-world-node-pack", "example.engineering-showcase-node-pack"),
        question_packs=("question-pack.document",),
        design_packs=("design-pack.text-document",),
        examples=("document-to-schema", "grounded-document-extraction"),
        benchmarks=("benchmark.document-extraction",),
        arena_tasks=("arena.invoice-accounting-schema",),
    ),
    recipe(
        NAMESPACE,
        "render",
        "Document render and visual verification",
        "Resolve assets, paginate, render, inspect every page, compare visual properties, and publish exact output provenance.",
        ("artifact.document-source",),
        ("artifact.verified-document",),
        (
            "document.assets",
            "document.layout",
            "document.render",
            "document.visual-verify",
            "document.publish",
        ),
        ("dag.generate.report", "dag.evaluate.regression", "dag.govern.provenance"),
        ("template.document-intelligence",),
        node_packs=("example.engineering-showcase-node-pack",),
        examples=("document-render-and-verify",),
        arena_tasks=("arena.document-render-and-verify",),
    ),
    recipe(
        NAMESPACE,
        "redact",
        "Document privacy and redaction",
        "Detect sensitive spans and regions, apply irreversible or reversible policy, render, and independently scan for residual leakage.",
        ("artifact.document-corpus",),
        ("artifact.redacted-documents",),
        (
            "document.detect-sensitive",
            "document.redact",
            "document.render",
            "document.leakage-check",
            "document.audit",
        ),
        ("dag.govern.privacy", "dag.prepare.verify", "dag.evaluate.safety"),
        ("template.document-intelligence", "template.compliance-evidence"),
        node_packs=("example.extended-arena-node-pack",),
        question_packs=("question-pack.document",),
        examples=("pii-redaction",),
        arena_tasks=("arena.pii-redaction",),
    ),
)
PACK = specialized_pack(
    "document_intelligence",
    "Document intelligence",
    "Document ingestion, OCR and layout, grounded extraction, rendering, visual verification, redaction, and provenance.",
    domain_packs=(
        "domain-pack.documents-media",
        "domain-pack.data-integration",
        "domain-pack.llm-agent",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "document",
        "pdf",
        "docx",
        "invoice",
        "ocr",
        "layout",
        "table extraction",
        "form",
        "redaction",
        "render",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
