"""Specialized package for learning content, assessment, and bounded adaptation."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "education-assessment"
FEATURES = (
    feature(
        NAMESPACE,
        "learning-contract",
        "Learning contract",
        "Profile learners, prerequisites, objectives, standards, modality, accommodations, context, and prohibited inference.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "assessment-design",
        "Assessment design",
        "Profile constructs, blueprint, item formats, rubrics, difficulty, exposure, security, scoring, and consequential use.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "evidence-profile",
        "Learning evidence profile",
        "Measure attempts, missingness, response processes, rater agreement, accessibility, subgroup representation, and feedback timing.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "content-embedding",
        "Learning-content embedding",
        "Optional content and objective embedding for discovery under an exact embedding-space identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "objective-coverage",
        "Objective coverage",
        "Declared learning objectives represented with sufficient depth, modality, and assessment evidence.",
        "maximize",
        "ratio",
        scope="scope.curriculum",
    ),
    metric(
        NAMESPACE,
        "scoring-agreement",
        "Scoring agreement",
        "Agreement with frozen rubrics, adjudicated experts, and accepted alternate answers by item slice.",
        "maximize",
        "ratio",
        scope="scope.item",
    ),
    metric(
        NAMESPACE,
        "accessibility-failures",
        "Accessibility failures",
        "Content or assessment failures against declared accommodations and accessibility checks.",
        "minimize",
        "count",
        scope="scope.release",
    ),
    metric(
        NAMESPACE,
        "subgroup-impact",
        "Subgroup impact disparity",
        "Maximum predeclared validity, opportunity, scoring, or outcome disparity requiring review.",
        "minimize",
        "score",
        scope="scope.subgroup",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "content",
        "Learning content gate",
        "Reject content without objective alignment, source grounding, accessibility, age/context fit, and misconception checks.",
        (METRICS[0].id, METRICS[2].id),
        oracle_kind="human",
    ),
    gate(
        NAMESPACE,
        "assessment",
        "Assessment decision gate",
        "Escalate consequential scoring or adaptation without rubric agreement, validity, subgroup analysis, appeal, and accountable educator review.",
        (METRICS[1].id, METRICS[3].id),
        oracle_kind="human",
        decision="escalate",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "curriculum",
        "Learning-content pipeline",
        "Map objectives and prerequisites, retrieve grounded sources, generate diverse modalities, check misconceptions and accessibility, and obtain educator approval.",
        ("artifact.learning-objectives",),
        ("artifact.learning-content",),
        (
            "education.map-objectives",
            "education.retrieve",
            "education.generate",
            "education.misconception-check",
            "education.accessibility",
            "education.review",
        ),
        (
            "dag.integrate.enrich.knowledge",
            "dag.generate",
            "dag.evaluate.safety",
            "dag.human.review",
        ),
        ("template.education-assessment", "template.knowledge-retrieval"),
        design_packs=("design-pack.text-document", "design-pack.fairness-risk"),
        arena_tasks=("arena.education-assessment",),
    ),
    recipe(
        NAMESPACE,
        "assessment",
        "Assessment authoring and validation",
        "Freeze a construct blueprint, author and review items, generate adversarial and alternate responses, calibrate difficulty, validate rubrics, and control exposure.",
        ("artifact.assessment-blueprint",),
        ("artifact.validated-assessment",),
        (
            "education.blueprint",
            "education.author-items",
            "education.adversarial-test",
            "education.calibrate",
            "education.validate-rubric",
            "education.secure",
        ),
        ("dag.generate.synthetic", "dag.evaluate.model", "dag.evaluate.outer", "dag.human.review"),
        ("template.education-assessment", "template.llm-evaluation-harness"),
        design_packs=(
            "design-pack.synthetic-data",
            "design-pack.evaluation-error",
            "design-pack.fairness-risk",
        ),
        arena_tasks=("arena.education-assessment",),
    ),
    recipe(
        NAMESPACE,
        "feedback",
        "Bounded learning feedback loop",
        "Score against an explicit rubric, expose evidence and uncertainty, provide actionable feedback, route ambiguity, monitor outcomes, and prevent unsupported high-stakes inference.",
        ("artifact.learner-response",),
        ("artifact.learning-feedback",),
        (
            "education.validate-response",
            "education.score",
            "education.explain",
            "education.feedback",
            "education.escalate",
            "education.monitor",
        ),
        (
            "dag.evaluate.llm-harness",
            "dag.human.review",
            "dag.operate.observe",
            "dag.govern.privacy",
        ),
        ("template.education-assessment",),
        arena_tasks=("arena.education-assessment",),
        limitations=(
            "The package must not infer protected, clinical, or life-impacting traits from learning behavior.",
        ),
    ),
)
PACK = specialized_pack(
    "education_assessment",
    "Education and assessment",
    "Learning objectives, grounded content, assessment design, rubric validation, accessibility, feedback, adaptation, and educator-governed decisions.",
    domain_packs=(
        "domain-pack.documents-media",
        "domain-pack.llm-agent",
        "domain-pack.ai-ml",
        "domain-pack.business-human-workflow",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "education",
        "learning",
        "curriculum",
        "assessment",
        "quiz",
        "rubric",
        "student",
        "tutoring",
        "instructional design",
        "grading",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
    readiness="catalog",
    limitations=(
        "The package provides design-time contracts only; high-stakes assessment requires validated instruments, qualified educators, accessibility review, appeal, privacy governance, and jurisdiction-specific controls.",
    ),
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
