"""Specialized package for financial data, risk, fraud, and governed decisions."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "finance-risk-fraud"
FEATURES = (
    feature(
        NAMESPACE,
        "ledger-contract",
        "Ledger and transaction contract",
        "Profile accounts, currencies, signs, effective and posting times, reversals, settlements, identities, and reconciliation keys.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "risk-decision",
        "Risk decision surface",
        "Profile exposure, horizon, labels, costs, limits, overrides, latency, affected parties, and regulatory constraints.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "market-regime",
        "Market and regime profile",
        "Measure calendar, corporate-action, liquidity, volatility, drift, dependency, tail, and stress-regime characteristics.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "case-embedding",
        "Financial case embedding",
        "Optional redacted case-pattern embedding for historical discovery under an exact embedding-space identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "unreconciled-value",
        "Unreconciled value",
        "Absolute value remaining unmatched, duplicated, mistimed, or unexplained after reconciliation.",
        "minimize",
        "currency",
        scope="scope.ledger",
    ),
    metric(
        NAMESPACE,
        "expected-cost",
        "Decision expected cost",
        "Task-specific false-positive, false-negative, delay, loss, and intervention cost under declared weights.",
        "minimize",
        "currency",
        scope="scope.decision",
    ),
    metric(
        NAMESPACE,
        "calibration",
        "Risk calibration",
        "Agreement between predicted and observed risk by horizon, amount, regime, and protected review slice.",
        "maximize",
        "score",
        scope="scope.slice",
    ),
    metric(
        NAMESPACE,
        "control-violations",
        "Financial control violations",
        "Limit, authority, segregation, audit, fairness, privacy, or prohibited-use failures.",
        "minimize",
        "count",
        scope="scope.release",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "ledger",
        "Ledger integrity gate",
        "Reject financial aggregates with unexplained imbalance, duplication, currency, sign, or effective-time failures.",
        (METRICS[0].id,),
        oracle_kind="exact",
    ),
    gate(
        NAMESPACE,
        "risk",
        "Risk decision gate",
        "Escalate consequential risk or fraud decisions without calibrated cost evidence, independent controls, explanation, appeal, and accountable authority.",
        (METRICS[1].id, METRICS[2].id, METRICS[3].id),
        oracle_kind="human",
        decision="escalate",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "reconcile",
        "Financial reconciliation",
        "Normalize signed amounts and time semantics, match transactions, explain breaks, preserve double-entry invariants, and publish exception evidence.",
        ("artifact.financial-transactions",),
        ("artifact.reconciled-ledger",),
        (
            "finance.normalize",
            "finance.match",
            "finance.balance",
            "finance.explain-break",
            "finance.publish",
        ),
        ("dag.integrate.reconcile", "dag.prepare.verify", "dag.govern.provenance"),
        ("template.fraud-risk", "template.data-quality"),
        node_packs=("example.extended-arena-node-pack",),
        question_packs=("question-pack.transaction", "question-pack.datetime"),
        examples=("transaction-reconciliation",),
        arena_tasks=("arena.transaction-reconciliation",),
    ),
    recipe(
        NAMESPACE,
        "fraud",
        "Fraud and abuse decisioning",
        "Construct leakage-safe labels, generate entity and temporal signals, compare rules and models, calibrate costs, review adverse slices, and route uncertain cases.",
        ("artifact.transaction-events",),
        ("artifact.fraud-risk-decisions",),
        (
            "finance.label",
            "finance.entity-features",
            "finance.score",
            "finance.calibrate",
            "finance.explain",
            "finance.review",
        ),
        ("dag.learn.classification", "dag.learn.anomaly", "dag.evaluate.model", "dag.human.review"),
        ("template.fraud-risk",),
        question_packs=("question-pack.transaction",),
        design_packs=(
            "design-pack.target-labels",
            "design-pack.validation-splits",
            "design-pack.fairness-risk",
        ),
        arena_tasks=("arena.fraud-risk-decision",),
        limitations=(
            "The template does not authorize adverse action and requires domain-specific legal, fairness, and appeal controls.",
        ),
    ),
    recipe(
        NAMESPACE,
        "forecast-stress",
        "Financial forecast and stress analysis",
        "Align market calendars and vintages, backtest without look-ahead, model uncertainty and tails, run fixed stress scenarios, and publish bounded exposure evidence.",
        ("artifact.financial-time-series",),
        ("artifact.financial-stress-report",),
        (
            "finance.calendar",
            "finance.vintage",
            "finance.backtest",
            "finance.forecast",
            "finance.stress",
            "finance.report",
        ),
        (
            "dag.learn.forecast",
            "dag.generate.scenario",
            "dag.evaluate.model",
            "dag.generate.report",
        ),
        ("template.time-series-forecasting", "template.scientific-experiment"),
        node_packs=("example.real-world-node-pack",),
        design_packs=("design-pack.time-series", "design-pack.robustness-stability"),
        examples=("calibrated-time-series-forecast",),
        arena_tasks=("arena.calibrated-forecast",),
    ),
)
PACK = specialized_pack(
    "finance_risk_fraud",
    "Finance, risk, and fraud",
    "Ledger integrity, reconciliation, fraud and abuse detection, calibrated risk decisions, financial forecasting, stress testing, and control evidence.",
    domain_packs=(
        "domain-pack.data-integration",
        "domain-pack.ai-ml",
        "domain-pack.security-compliance",
        "domain-pack.business-human-workflow",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "finance",
        "financial",
        "ledger",
        "transaction",
        "reconciliation",
        "fraud",
        "credit risk",
        "market risk",
        "stress test",
        "portfolio",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
    limitations=(
        "Bundled fixtures use synthetic or simplified data and do not constitute trading, lending, accounting, audit, or regulatory advice.",
    ),
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
