"""Specialized package for game rules, simulation, playtesting, and release."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "game-engineering"
FEATURES = (
    feature(
        NAMESPACE,
        "state-space",
        "Game state space",
        "Profile entities, actions, transitions, randomness, persistence, networking, progression, and reachable-state boundaries.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "content-build",
        "Content and build profile",
        "Measure code, levels, assets, localization, targets, save versions, dependencies, and build reproducibility.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "playtest-surface",
        "Playtest surface",
        "Profile roles, levels, difficulty, devices, sessions, replays, bots, player slices, and human evidence.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "design-embedding",
        "Game design embedding",
        "Optional design/telemetry embedding for historical retrieval under an exact embedding-space identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "deterministic-replay",
        "Deterministic replay",
        "Replays producing the expected state and outcome hashes under the declared determinism contract.",
        "maximize",
        "ratio",
        scope="scope.replay",
    ),
    metric(
        NAMESPACE,
        "crash-free",
        "Crash-free sessions",
        "Sessions completing without crash, hang, corrupt save, or fatal desynchronization.",
        "maximize",
        "ratio",
        scope="scope.session",
    ),
    metric(
        NAMESPACE,
        "runtime",
        "Runtime performance",
        "Frame time, input latency, load time, memory, and network performance against target budgets.",
        "minimize",
        "milliseconds",
        scope="scope.runtime",
    ),
    metric(
        NAMESPACE,
        "balance-gap",
        "Balance gap",
        "Maximum predeclared disparity across roles, matchups, strategies, progression, or economy slices.",
        "minimize",
        "ratio",
        scope="scope.playtest",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "functional",
        "Game functional gate",
        "Reject builds that fail deterministic replay, crash, save, migration, networking, or accessibility requirements.",
        (METRICS[0].id, METRICS[1].id, METRICS[2].id),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "release",
        "Game release gate",
        "Escalate release when balance, exploit, safety, accessibility, or structured human playtest evidence is insufficient.",
        (METRICS[3].id,),
        oracle_kind="human",
        decision="escalate",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "build",
        "Reproducible game build",
        "Bind rules, content, dependencies, targets, save schemas, and build environments into versioned game artifacts.",
        ("artifact.game-design",),
        ("artifact.game-build",),
        ("game.state-contract", "game.content-closure", "game.build", "game.save-migration"),
        ("dag.serve.deploy", "dag.evaluate.regression", "dag.govern.provenance"),
        ("template.game-build-playtest", "template.deployment-release"),
        arena_tasks=("arena.game-build-playtest",),
        limitations=(
            "Engine-specific builds require Unity, Unreal, Godot, or another runtime adapter.",
        ),
    ),
    recipe(
        NAMESPACE,
        "playtest",
        "Automated replay and playtest",
        "Run deterministic replays, bounded bots, edge-state generation, economy simulations, balance analysis, and structured human playtests.",
        ("artifact.game-build",),
        ("artifact.game-playtest-report",),
        (
            "game.replay",
            "game.bot-playtest",
            "game.edge-case",
            "game.economy",
            "game.balance",
            "game.human-playtest",
        ),
        (
            "dag.evaluate.regression",
            "dag.generate.scenario",
            "dag.learn.reinforcement",
            "dag.evaluate.human",
        ),
        ("template.game-build-playtest",),
        node_packs=("example.frontier-domain-node-pack",),
        examples=("gameplay-replay-and-balance",),
        arena_tasks=("arena.game-build-playtest",),
        limitations=(
            "The local fixture measures deterministic rules and a tiny balance sample; subjective fun requires structured human evidence.",
        ),
    ),
    recipe(
        NAMESPACE,
        "release",
        "Game quality and release gate",
        "Compare control and candidate builds on identical replays, devices, performance, accessibility, safety, and rollback checks.",
        ("artifact.game-build",),
        ("artifact.game-release-evidence",),
        (
            "game.regression",
            "game.performance",
            "game.accessibility",
            "game.safety",
            "game.release",
            "game.rollback",
        ),
        (
            "dag.evaluate.regression",
            "dag.evaluate.safety",
            "dag.serve.deploy",
            "dag.operate.observe",
        ),
        ("template.game-build-playtest", "template.qa-engineering"),
        arena_tasks=("arena.game-build-playtest",),
    ),
)
PACK = specialized_pack(
    "game_engineering",
    "Game engineering",
    "Game-state contracts, reproducible builds, replay testing, bot and human playtests, balance, performance, accessibility, release, and rollback.",
    domain_packs=(
        "domain-pack.platform-release",
        "domain-pack.frontend-browser",
        "domain-pack.science-optimization",
        "domain-pack.ai-ml",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "game",
        "video game",
        "gameplay",
        "playtest",
        "replay",
        "level",
        "balance",
        "matchmaking",
        "economy",
        "unity",
        "unreal",
        "godot",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
