"""Specialized package for geospatial and temporal validation and enrichment."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "geospatial-temporal"
FEATURES = (
    feature(
        NAMESPACE,
        "spatial-profile",
        "Spatial profile",
        "Profile addresses, coordinates, geometry types, CRS, extents, resolution, boundaries, and topology defects.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "temporal-profile",
        "Temporal profile",
        "Profile timestamp formats, time zones, cadence, gaps, lateness, daylight transitions, and boundary vintages.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "authority-vintage",
        "Authority and vintage",
        "Record reference authority, publication date, effective interval, geographic coverage, match codes, and licensing.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "place-time-embedding",
        "Place-time task embedding",
        "Optional redacted place-time semantics for historical retrieval under an exact embedding-space identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "match-coverage",
        "Reference match coverage",
        "Records with an accepted authoritative or explicitly qualified reference match.",
        "maximize",
        "ratio",
        scope="scope.record",
    ),
    metric(
        NAMESPACE,
        "false-match",
        "False-match rate",
        "Sampled or independently verified incorrect place, address, boundary, or event matches.",
        "minimize",
        "ratio",
        scope="scope.record",
    ),
    metric(
        NAMESPACE,
        "topology-validity",
        "Topology validity",
        "Geometries and joins satisfying declared CRS, predicate, multiplicity, and topology contracts.",
        "maximize",
        "ratio",
        scope="scope.dataset",
    ),
    metric(
        NAMESPACE,
        "temporal-validity",
        "Temporal validity",
        "Records satisfying event-time, time-zone, cadence, lateness, and effective-date contracts.",
        "maximize",
        "ratio",
        scope="scope.dataset",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "reference",
        "Place and time reference gate",
        "Reject authoritative claims without exact source, vintage, match, uncertainty, and unresolved-reason evidence.",
        (METRICS[0].id, METRICS[1].id),
        oracle_kind="external-authority",
    ),
    gate(
        NAMESPACE,
        "product",
        "Geospatial-temporal product gate",
        "Reject output that fails CRS, geometry, spatial-predicate, event-time, or boundary-vintage checks.",
        (METRICS[2].id, METRICS[3].id),
        oracle_kind="property",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "address-place",
        "Address and place validation",
        "Parse and normalize address and place fields, resolve candidates, preserve match codes, and sample unresolved and accepted results.",
        ("artifact.raw-records",),
        ("artifact.geospatial-dataset",),
        ("geo.parse-address", "geo.normalize", "geo.reference-match", "geo.geocode", "geo.verify"),
        ("dag.integrate.enrich.geospatial", "dag.prepare.verify", "dag.integrate.enrich.identity"),
        ("template.data-quality", "template.geospatial-analytics"),
        node_packs=("example.real-world-node-pack",),
        question_packs=("question-pack.postal-address", "question-pack.geography"),
        design_packs=("design-pack.geospatial",),
        examples=("address-reference-verification", "exact-gis-boundary-resolution"),
        arena_tasks=("arena.usps-address-verification", "arena.exact-gis-boundary-resolution"),
        limitations=(
            "Offline fixtures are not USPS, Census, national mapping, or other authoritative production responses.",
        ),
    ),
    recipe(
        NAMESPACE,
        "geotemporal-enrichment",
        "Geospatial and temporal enrichment",
        "Resolve location, CRS, boundaries, time zone, local/UTC features, effective dates, and authorized place-time context with provenance.",
        ("artifact.geospatial-dataset",),
        ("artifact.enriched-dataset",),
        (
            "geo.boundary",
            "geo.timezone",
            "geo.temporal-features",
            "geo.place-time-join",
            "geo.provenance",
        ),
        (
            "dag.integrate.enrich.geotemporal",
            "dag.integrate.enrich.temporal",
            "dag.govern.provenance",
        ),
        ("template.geospatial-analytics", "template.event-driven-system"),
        node_packs=("example.engineering-showcase-node-pack",),
        question_packs=("question-pack.datetime", "question-pack.geography"),
        examples=("geotemporal-enrichment",),
        arena_tasks=("arena.geospatial-enrichment",),
    ),
    recipe(
        NAMESPACE,
        "spatial-product",
        "Spatial analysis and map product",
        "Repair and transform geometries, join with explicit predicates, derive spatial evidence, quantify uncertainty, render, and publish data and maps.",
        ("artifact.geospatial-dataset",),
        ("artifact.spatial-product",),
        (
            "geo.repair",
            "geo.transform",
            "geo.spatial-join",
            "geo.analyze",
            "geo.uncertainty",
            "geo.render",
        ),
        ("dag.integrate.join", "dag.learn.feature", "dag.generate.report", "dag.prepare.verify"),
        ("template.geospatial-analytics",),
        design_packs=("design-pack.geospatial", "design-pack.robustness-stability"),
        arena_tasks=("arena.geospatial-data-product",),
    ),
)
PACK = specialized_pack(
    "geospatial_temporal",
    "Geospatial and temporal",
    "Address, place, coordinate, boundary, time-zone, event-time, place-time enrichment, spatial analysis, and map products.",
    domain_packs=(
        "domain-pack.data-integration",
        "domain-pack.science-optimization",
        "domain-pack.documents-media",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "gis",
        "geospatial",
        "address",
        "zip code",
        "city",
        "state",
        "county",
        "coordinates",
        "timezone",
        "datetime",
        "geotemporal",
        "map",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
    readiness="credentialed-connector",
    limitations=(
        "Local fixtures prove typed seams only; authoritative address, boundary, time-zone, and event enrichment requires current licensed sources and scoped connectors.",
    ),
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
