"""Specialized package for bounded healthcare and biomedical evidence workflows."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "healthcare-biomedical"
FEATURES = (
    feature(
        NAMESPACE,
        "cohort-and-purpose",
        "Cohort and intended purpose",
        "Profile population, setting, inclusion, exclusion, intervention, comparator, outcome, users, and prohibited uses.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "clinical-data-quality",
        "Clinical data quality",
        "Profile coding systems, units, ranges, timelines, missingness, site effects, leakage, censoring, and label provenance.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "risk-and-authority",
        "Clinical risk and authority",
        "Record consequence severity, uncertainty, human decision rights, escalation, privacy, and applicable validation obligations.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "evidence-embedding",
        "Biomedical evidence embedding",
        "Optional de-identified question and evidence embedding for discovery under an exact representation identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "cohort-validity",
        "Cohort validity",
        "Records satisfying the frozen population, temporal, coding, consent, and leakage contract.",
        "maximize",
        "ratio",
        scope="scope.cohort",
    ),
    metric(
        NAMESPACE,
        "subgroup-performance",
        "Subgroup performance",
        "Task-appropriate discrimination, calibration, error, and abstention by predeclared clinical subgroup.",
        "maximize",
        "score",
        scope="scope.subgroup",
    ),
    metric(
        NAMESPACE,
        "evidence-grounding",
        "Evidence grounding",
        "Material claims linked to exact source, version, population, and applicability evidence.",
        "maximize",
        "ratio",
        scope="scope.claim",
    ),
    metric(
        NAMESPACE,
        "unsafe-decision",
        "Unsafe decision rate",
        "Decisions violating contraindication, uncertainty, authority, escalation, or declared safety constraints.",
        "minimize",
        "ratio",
        scope="scope.decision",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "evidence",
        "Biomedical evidence gate",
        "Reject evidence claims without cohort validity, exact grounding, uncertainty, and applicability boundaries.",
        (METRICS[0].id, METRICS[2].id),
        oracle_kind="cross-implementation",
    ),
    gate(
        NAMESPACE,
        "clinical-use",
        "Clinical-use authority gate",
        "Escalate every consequential clinical recommendation without independent validation, subgroup evidence, abstention, and accountable qualified review.",
        (METRICS[1].id, METRICS[3].id),
        oracle_kind="human",
        decision="escalate",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "cohort",
        "Clinical cohort construction",
        "Freeze intended use, map coding and temporal semantics, reconcile episodes, enforce inclusion and leakage rules, and publish cohort provenance.",
        ("artifact.clinical-records",),
        ("artifact.validated-clinical-cohort",),
        (
            "health.scope",
            "health.code-map",
            "health.timeline",
            "health.cohort",
            "health.leakage-check",
            "health.provenance",
        ),
        ("dag.prepare.schema", "dag.prepare.verify", "dag.integrate.join", "dag.govern.privacy"),
        ("template.healthcare-evidence", "template.data-quality"),
        question_packs=("question-pack.datetime", "question-pack.generic-tabular"),
        design_packs=(
            "design-pack.task-contract",
            "design-pack.validation-splits",
            "design-pack.reproducibility-governance",
        ),
        arena_tasks=("arena.healthcare-decision-support",),
    ),
    recipe(
        NAMESPACE,
        "evidence-synthesis",
        "Grounded biomedical evidence synthesis",
        "Define the question, search and screen under a protocol, extract source-bound findings, assess bias and applicability, and synthesize uncertainty.",
        ("artifact.biomedical-question",),
        ("artifact.biomedical-evidence-dossier",),
        (
            "health.question",
            "health.retrieve",
            "health.screen",
            "health.extract",
            "health.bias",
            "health.synthesize",
        ),
        (
            "dag.acquire.document",
            "dag.integrate.enrich.knowledge",
            "dag.evaluate.outer",
            "dag.human.review",
        ),
        ("template.healthcare-evidence", "template.knowledge-retrieval"),
        question_packs=("question-pack.document",),
        design_packs=(
            "design-pack.text-document",
            "design-pack.evaluation-error",
            "design-pack.decision-handoff",
        ),
        arena_tasks=("arena.healthcare-decision-support",),
    ),
    recipe(
        NAMESPACE,
        "decision-support",
        "Bounded clinical decision support",
        "Validate input completeness, retrieve applicable evidence, estimate uncertainty, surface alternatives and contraindications, abstain when required, and record clinician disposition.",
        ("artifact.clinical-case",),
        ("artifact.clinical-decision-support-evidence",),
        (
            "health.validate-case",
            "health.retrieve-evidence",
            "health.assess",
            "health.abstain",
            "health.review",
            "health.monitor",
        ),
        ("dag.evaluate.model", "dag.evaluate.safety", "dag.human.review", "dag.operate.observe"),
        ("template.healthcare-evidence", "template.llm-evaluation-harness"),
        design_packs=(
            "design-pack.fairness-risk",
            "design-pack.interpretability",
            "design-pack.monitoring-feedback",
        ),
        arena_tasks=("arena.healthcare-decision-support",),
        limitations=(
            "This is an evidence architecture, not a medical device, diagnosis, treatment recommendation, or substitute for qualified clinical review.",
        ),
    ),
)
PACK = specialized_pack(
    "healthcare_biomedical",
    "Healthcare and biomedical evidence",
    "Cohort construction, biomedical evidence synthesis, clinical-model evaluation, bounded decision support, privacy, and accountable review.",
    domain_packs=(
        "domain-pack.documents-media",
        "domain-pack.data-integration",
        "domain-pack.ai-ml",
        "domain-pack.security-compliance",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "healthcare",
        "biomedical",
        "clinical",
        "patient",
        "cohort",
        "diagnosis",
        "medical evidence",
        "ehr",
        "fhir",
        "clinical trial",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
    readiness="catalog",
    limitations=(
        "The package supplies design-time evidence contracts only; regulated or clinical use requires jurisdiction-specific governance, validated data and systems, qualified oversight, and production adapters.",
    ),
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
