"""Specialized package for grounded knowledge systems and reproducible research."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "knowledge-research"
FEATURES = (
    feature(
        NAMESPACE,
        "question-scope",
        "Question and claim scope",
        "Profile decisions, claims, populations, time windows, jurisdictions, uncertainty, freshness, and acceptable abstention.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "source-landscape",
        "Source landscape",
        "Profile source authority, independence, access, format, date, version, coverage, conflicts, and retraction or correction risk.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "knowledge-structure",
        "Knowledge structure",
        "Measure entities, concepts, relations, provenance, temporal validity, contradictions, orphan claims, and update dependencies.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "claim-embedding",
        "Claim and source embedding",
        "Optional claim/source embedding for discovery under an exact embedding-space identity; never treated as proof.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "claim-grounding",
        "Claim grounding",
        "Material claims linked to exact source spans, versions, retrieval times, and applicability notes.",
        "maximize",
        "ratio",
        scope="scope.claim",
    ),
    metric(
        NAMESPACE,
        "source-coverage",
        "Source coverage",
        "Predeclared evidence perspectives, authorities, dates, and disconfirming searches represented in the dossier.",
        "maximize",
        "ratio",
        scope="scope.question",
    ),
    metric(
        NAMESPACE,
        "conflict-closure",
        "Conflict closure",
        "Detected material conflicts explicitly resolved, scoped, or left visible with decision impact.",
        "maximize",
        "ratio",
        scope="scope.conflict",
    ),
    metric(
        NAMESPACE,
        "reproducibility",
        "Research reproducibility",
        "Queries, sources, snapshots, extraction, transformations, analyses, and outputs reproducible from receipts.",
        "maximize",
        "ratio",
        scope="scope.study",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "claim",
        "Grounded claim gate",
        "Reject unsupported, stale, scope-mismatched, or provenance-free material claims.",
        (METRICS[0].id, METRICS[2].id),
        oracle_kind="cross-implementation",
    ),
    gate(
        NAMESPACE,
        "research",
        "Research decision gate",
        "Escalate high-consequence conclusions without adequate source coverage, reproducibility, uncertainty, and accountable domain review.",
        (METRICS[1].id, METRICS[3].id),
        oracle_kind="human",
        decision="escalate",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "knowledge-base",
        "Provenance-first knowledge base",
        "Ingest permitted sources, resolve entities and concepts, extract source-bound relations, retain temporal validity and conflicts, and publish update lineage.",
        ("artifact.source-corpus",),
        ("artifact.knowledge-base",),
        (
            "knowledge.ingest",
            "knowledge.resolve",
            "knowledge.extract",
            "knowledge.provenance",
            "knowledge.conflict",
            "knowledge.update",
        ),
        (
            "dag.acquire.document",
            "dag.integrate.enrich.knowledge",
            "dag.integrate.enrich.identity",
            "dag.govern.provenance",
        ),
        ("template.knowledge-retrieval", "template.document-intelligence"),
        node_packs=("example.engineering-showcase-node-pack",),
        question_packs=("question-pack.document",),
        examples=("grounded-document-extraction",),
        arena_tasks=("arena.grounded-knowledge-system",),
    ),
    recipe(
        NAMESPACE,
        "research",
        "Reproducible research dossier",
        "Freeze the question and protocol, discover diverse sources, extract and reconcile evidence, run declared analysis, challenge conclusions, and publish receipts.",
        ("artifact.research-question",),
        ("artifact.research-dossier",),
        (
            "research.protocol",
            "research.discover",
            "research.extract",
            "research.analyze",
            "research.challenge",
            "research.publish",
        ),
        ("dag.acquire.web", "dag.acquire.document", "dag.evaluate.outer", "dag.generate.report"),
        ("template.scientific-experiment", "template.knowledge-retrieval"),
        node_packs=("example.extended-arena-node-pack",),
        design_packs=(
            "design-pack.task-contract",
            "design-pack.evaluation-error",
            "design-pack.reproducibility-governance",
        ),
        examples=("scientific-experiment",),
        arena_tasks=("arena.scientific-experiment",),
    ),
    recipe(
        NAMESPACE,
        "grounded-answer",
        "Grounded answer with abstention",
        "Decompose the question, retrieve eligible evidence, synthesize only supported claims, expose conflicts and uncertainty, and abstain outside the evidence boundary.",
        ("artifact.knowledge-query",),
        ("artifact.grounded-answer",),
        (
            "knowledge.decompose",
            "knowledge.retrieve",
            "knowledge.rerank",
            "knowledge.synthesize",
            "knowledge.cite",
            "knowledge.abstain",
        ),
        (
            "dag.integrate.enrich.knowledge",
            "dag.evaluate.llm-harness",
            "dag.evaluate.outer",
            "dag.human.review",
        ),
        ("template.knowledge-retrieval", "template.llm-evaluation-harness"),
        examples=("grounded-document-extraction", "duecare-llm-evaluation-harness"),
        arena_tasks=("arena.grounded-knowledge-system", "arena.llm-evaluation-harness"),
    ),
)
PACK = specialized_pack(
    "knowledge_research",
    "Knowledge and research",
    "Provenance-first knowledge bases, evidence discovery, conflict-aware synthesis, reproducible research dossiers, grounded answers, and abstention.",
    domain_packs=(
        "domain-pack.documents-media",
        "domain-pack.llm-agent",
        "domain-pack.data-integration",
        "domain-pack.science-optimization",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "research",
        "knowledge base",
        "knowledge graph",
        "evidence synthesis",
        "literature review",
        "grounded answer",
        "citations",
        "fact checking",
        "rag",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
