"""Specialized capability pack for LLM systems, harnesses, and evaluation."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "llm-engineering"

FEATURES = (
    feature(
        NAMESPACE,
        "task-mode",
        "LLM task mode",
        "Classify generation, extraction, retrieval, tool use, judging, tutoring, or agent trajectory semantics.",
        "category",
    ),
    feature(
        NAMESPACE,
        "context-profile",
        "Context profile",
        "Measure source count, token length, structure, freshness, authority, duplication, and retrieval boundaries.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "tool-authority",
        "Tool authority",
        "Enumerate tools, effects, permissions, secrets, and approval boundaries available to the system.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "scenario-surface",
        "Scenario surface",
        "Summarize normal, edge, adversarial, multilingual, long-context, and tool-failure scenario coverage.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "judge-dependence",
        "Judge dependence",
        "Measure shared model families, prompts, training signals, and likely correlated judge failures.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "contamination-risk",
        "Contamination risk",
        "Record candidate readability, benchmark exposure, retrieval leakage, and held-out evaluator isolation.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "response-shape",
        "Response shape",
        "Describe structured-output, citation, abstention, length, modality, and safety requirements.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "scenario-embedding",
        "Scenario embedding",
        "Optional embedding of redacted scenario semantics for diverse retrieval; exact model, revision, dimensions, distance, and source digest remain mandatory.",
    ),
)

METRICS = (
    metric(
        NAMESPACE,
        "task-acceptance",
        "Task acceptance",
        "Share of scenarios accepted by the separately identified task oracle.",
        "maximize",
        "ratio",
        scope="scope.scenario",
    ),
    metric(
        NAMESPACE,
        "groundedness",
        "Groundedness",
        "Share of material claims supported by authorized source evidence under the fixed citation evaluator.",
        "maximize",
        "ratio",
        scope="scope.response",
    ),
    metric(
        NAMESPACE,
        "adversarial-failure",
        "Adversarial failure rate",
        "Share of adversarial scenarios causing a declared safety, policy, or integrity failure.",
        "minimize",
        "ratio",
        scope="scope.stress",
    ),
    metric(
        NAMESPACE,
        "judge-agreement",
        "Judge agreement",
        "Agreement and calibrated disagreement across independent judges and human adjudication samples.",
        "maximize",
        "ratio",
        scope="scope.evaluation",
    ),
    metric(
        NAMESPACE,
        "cost-per-accepted",
        "Cost per accepted result",
        "Measured model, tool, and infrastructure cost divided by accepted outputs.",
        "minimize",
        "currency-per-result",
        scope="scope.run",
    ),
    metric(
        NAMESPACE,
        "latency",
        "End-to-end latency",
        "Measured end-to-end latency including retrieval, tools, generation, and independent evaluation.",
        "minimize",
        "milliseconds",
        scope="scope.run",
    ),
    metric(
        NAMESPACE,
        "sealed-holdout-acceptance",
        "Sealed holdout acceptance",
        "Acceptance on candidate-unreadable scenarios and evaluator infrastructure.",
        "maximize",
        "ratio",
        scope="scope.holdout",
    ),
)

GATES = (
    gate(
        NAMESPACE,
        "grounded-response",
        "Grounded response gate",
        "Reject consequential outputs when task acceptance or source grounding fails.",
        (METRICS[0].id, METRICS[1].id),
        oracle_kind="cross-implementation",
    ),
    gate(
        NAMESPACE,
        "adversarial-safety",
        "Adversarial safety gate",
        "Reject promotion when the fixed red-team suite exceeds its declared failure threshold.",
        (METRICS[2].id,),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "sealed-promotion",
        "Sealed promotion gate",
        "Reject promotion unless diverse judges, human samples, and candidate-unreadable holdouts satisfy the predeclared protocol.",
        (METRICS[3].id, METRICS[6].id),
        oracle_kind="human",
    ),
)

RECIPES = (
    recipe(
        NAMESPACE,
        "grounded-rag",
        "Grounded retrieval and generation",
        "Establish corpus authority, parse and index content, retrieve and rerank evidence, generate with citations, and independently verify claims.",
        ("artifact.document-corpus",),
        ("artifact.llm-system",),
        ("llm.retrieve", "llm.rerank", "llm.generate", "llm.cite", "llm.verify"),
        ("dag.learn.rag", "dag.integrate.enrich.knowledge", "dag.evaluate.rag"),
        ("template.knowledge-retrieval", "template.document-intelligence"),
        node_packs=(
            "example.engineering-showcase-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        question_packs=("question-pack.document",),
        design_packs=("design-pack.text-document", "design-pack.llm-harness"),
        examples=("grounded-document-extraction",),
        arena_tasks=("arena.grounded-knowledge-system",),
        limitations=(
            "Fixture retrieval and judging do not establish production factuality or safety.",
        ),
    ),
    recipe(
        NAMESPACE,
        "evaluation-red-team",
        "LLM evaluation and red-team harness",
        "Freeze scenarios, solution, development evaluation, improvement, promotion, and sealed outer-evaluation graphs with feedback firewalls.",
        ("artifact.llm-system",),
        ("artifact.llm-evaluation-report",),
        ("llm.scenario", "llm.evaluate", "llm.red-team", "llm.adjudicate", "llm.promote"),
        (
            "dag.evaluate.llm-harness",
            "dag.evaluate.safety",
            "dag.evaluate.judge",
            "dag.evaluate.outer",
        ),
        ("template.content-moderation", "template.cybersecurity-investigation"),
        node_packs=(
            "example.engineering-showcase-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        design_packs=(
            "design-pack.llm-harness",
            "design-pack.fairness-risk",
            "design-pack.robustness-stability",
        ),
        examples=("duecare-llm-evaluation-harness",),
        arena_tasks=("arena.content-policy-moderation", "arena.defensive-cyber-investigation"),
    ),
    recipe(
        NAMESPACE,
        "synthetic-curriculum",
        "Synthetic instruction and adversarial curriculum",
        "Generate, deduplicate, filter, balance, adversarially expand, and independently evaluate synthetic training examples before mixing.",
        ("artifact.validated-dataset",),
        ("artifact.llm-training-data",),
        (
            "llm.synthetic-generate",
            "llm.synthetic-filter",
            "llm.synthetic-balance",
            "llm.synthetic-verify",
        ),
        ("dag.generate.synthetic.text", "dag.generate.synthetic.adversarial", "dag.generate.label"),
        ("template.scientific-experiment",),
        node_packs=(
            "example.engineering-showcase-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        design_packs=("design-pack.synthetic-data", "design-pack.llm-harness"),
        examples=("synthetic-llm-curriculum",),
        arena_tasks=("arena.text-classification-pipeline",),
    ),
    recipe(
        NAMESPACE,
        "coding-agent-ab",
        "Coding-agent control/treatment arena",
        "Run paired control and SolutionGraph-context workspaces across compatible task, harness, model, and seed cells with sealed evaluation.",
        ("artifact.repository",),
        ("artifact.llm-evaluation-report",),
        ("agent.materialize", "agent.invoke", "agent.evaluate", "agent.compare", "agent.report"),
        ("dag.evaluate.agent", "dag.evaluate.outer", "dag.evaluate.human"),
        ("template.qa-engineering",),
        node_packs=("reference.core-node-pack",),
        design_packs=("design-pack.llm-harness", "design-pack.reproducibility-governance"),
        examples=("tested-code-repair",),
        agent_benchmarks=(
            "agent-benchmark.reference-smoke",
            "agent-benchmark.command-matrix-example",
        ),
        arena_tasks=("arena.repository-repair",),
        limitations=("The bundled smoke adapter is model-free and proves harness mechanics only.",),
    ),
)

PACK = specialized_pack(
    "llm_engineering",
    "LLM engineering",
    "Grounded RAG, agent and tool systems, synthetic curricula, DueCare-style evaluation, judging, red teaming, and sealed promotion harnesses.",
    domain_packs=(
        "domain-pack.llm-agent",
        "domain-pack.documents-media",
        "domain-pack.security-compliance",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "llm",
        "language model",
        "rag",
        "retrieval augmented",
        "agent",
        "tool use",
        "eval harness",
        "llm evaluation",
        "red team",
        "jailbreak",
        "llm as judge",
        "synthetic instruction data",
        "due care",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)

__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
