"""Specialized package for image, audio, video, and multimodal media."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "media-intelligence"
FEATURES = (
    feature(
        NAMESPACE,
        "stream-profile",
        "Media stream profile",
        "Profile containers, codecs, tracks, rates, dimensions, duration, channels, color, captions, and metadata.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "timeline-quality",
        "Timeline quality",
        "Measure monotonicity, gaps, overlap, drift, synchronization, and caption coverage.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "rights-policy",
        "Rights and policy profile",
        "Record source, ownership, consent, likeness, licensing, retention, audience, and content-policy boundaries.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "multimodal-embedding",
        "Multimodal content embedding",
        "Optional content embedding for search and diversity under an exact model and representation identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "integrity",
        "Media integrity",
        "Assets without structural corruption, missing tracks, invalid timestamps, or reference gaps.",
        "maximize",
        "ratio",
        scope="scope.asset",
    ),
    metric(
        NAMESPACE,
        "sync-error",
        "Synchronization error",
        "Measured audio, video, caption, and metadata timing error.",
        "minimize",
        "milliseconds",
        scope="scope.timeline",
    ),
    metric(
        NAMESPACE,
        "quality",
        "Perceptual and technical quality",
        "Fixed-reference or property-based picture, audio, continuity, and encoding quality.",
        "maximize",
        "score",
        scope="scope.asset",
    ),
    metric(
        NAMESPACE,
        "policy-violations",
        "Rights and policy violations",
        "Verified privacy, safety, licensing, or delivery-policy violations.",
        "minimize",
        "count",
        scope="scope.release",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "technical",
        "Technical media gate",
        "Reject assets that fail integrity, synchronization, caption, or declared quality constraints.",
        (METRICS[0].id, METRICS[1].id, METRICS[2].id),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "release",
        "Media release gate",
        "Reject publication without independent rights, privacy, safety, and policy evidence.",
        (METRICS[3].id,),
        oracle_kind="human",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "image-assurance",
        "Image intelligence and assurance",
        "Decode, orient, enhance, extract text and visual signals, verify quality and policy, and publish a source-bound report.",
        ("artifact.image-bundle",),
        ("artifact.media-assurance-report",),
        ("media.decode-image", "media.ocr", "media.inspect-image", "media.verify-image"),
        ("dag.acquire.document", "dag.prepare.parse", "dag.evaluate.safety"),
        ("template.image-processing",),
        node_packs=("example.real-world-node-pack",),
        design_packs=("design-pack.image-multimodal",),
        examples=("image-check-and-process",),
        benchmarks=("benchmark.image-assurance",),
        arena_tasks=("arena.image-assurance",),
    ),
    recipe(
        NAMESPACE,
        "audio-assurance",
        "Audio and speech assurance",
        "Decode, enhance, segment, transcribe, diarize, align, classify, and independently verify audio outputs.",
        ("artifact.audio-bundle",),
        ("artifact.media-assurance-report",),
        ("media.decode-audio", "media.segment-audio", "media.transcribe", "media.verify-audio"),
        ("dag.acquire.document", "dag.prepare.parse", "dag.evaluate.model"),
        ("template.audio-speech",),
        design_packs=("design-pack.image-multimodal",),
        arena_tasks=("arena.audio-speech-assurance",),
        limitations=("No production speech or audio runtime is bundled.",),
    ),
    recipe(
        NAMESPACE,
        "video-assurance",
        "Video timeline and caption assurance",
        "Probe streams, normalize timestamps, align modalities, verify captions and integrity, and produce versioned delivery evidence.",
        ("artifact.video-bundle",),
        ("artifact.media-assurance-report",),
        ("media.probe-video", "media.timeline", "media.align", "media.caption", "media.assure"),
        ("dag.acquire.document", "dag.prepare.verify", "dag.generate.report"),
        ("template.video-media-pipeline",),
        node_packs=("example.frontier-domain-node-pack",),
        examples=("video-media-assurance",),
        arena_tasks=("arena.video-media-assurance",),
        limitations=(
            "The fixture validates timeline metadata and does not execute a codec or establish perceptual quality.",
        ),
    ),
)
PACK = specialized_pack(
    "media_intelligence",
    "Media intelligence",
    "Image, audio, video, captions, multimodal extraction, transformation, assurance, rights, and delivery evidence.",
    domain_packs=(
        "domain-pack.documents-media",
        "domain-pack.ai-ml",
        "domain-pack.security-compliance",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "image",
        "audio",
        "video",
        "media",
        "speech",
        "caption",
        "transcription",
        "ocr",
        "multimodal",
        "transcode",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
