"""Specialized capability pack for ML systems, release, and feedback loops."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "ml-engineering"

FEATURES = (
    feature(
        NAMESPACE,
        "training-footprint",
        "Training footprint",
        "Summarize data, compute, memory, accelerator, wall-time, and artifact requirements.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "serving-contract",
        "Serving contract",
        "Record request/response types, batching, latency, throughput, and availability requirements.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "dependency-surface",
        "Dependency surface",
        "Count and classify model, binary, package, service, secret, and hardware dependencies.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "drift-sensitivity",
        "Drift sensitivity",
        "Identify feature, label, concept, calibration, and operational drift signals relevant to the model.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "rollback-readiness",
        "Rollback readiness",
        "Check artifact identity, compatibility, shadow evidence, and reversible promotion boundaries.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "feedback-delay",
        "Feedback delay",
        "Measure delay, censoring, and sampling bias between prediction and trustworthy outcome evidence.",
        "distribution",
    ),
    embedding_feature(
        NAMESPACE,
        "system-profile-embedding",
        "ML-system profile embedding",
        "Optional embedding of the deployment and monitoring profile for retrieving comparable historical releases.",
    ),
)

METRICS = (
    metric(
        NAMESPACE,
        "release-acceptance",
        "Release acceptance",
        "Share of fixed release cases passing quality, compatibility, policy, and operational gates.",
        "maximize",
        "ratio",
        scope="scope.release",
    ),
    metric(
        NAMESPACE,
        "serving-latency",
        "Serving latency",
        "Measured tail latency on the declared reference runtime and workload.",
        "minimize",
        "milliseconds",
        scope="scope.runtime",
    ),
    metric(
        NAMESPACE,
        "serving-cost",
        "Serving cost",
        "Measured cost per declared unit of accepted work.",
        "minimize",
        "currency-per-unit",
        scope="scope.runtime",
    ),
    metric(
        NAMESPACE,
        "recovery-time",
        "Recovery time",
        "Observed time to detect, halt, roll back, and verify a failed promotion.",
        "minimize",
        "seconds",
        scope="scope.recovery",
    ),
    metric(
        NAMESPACE,
        "drift-detection-delay",
        "Drift detection delay",
        "Delay between fixed drift onset and independently verified detection.",
        "minimize",
        "seconds",
        scope="scope.monitoring",
    ),
    metric(
        NAMESPACE,
        "synthetic-utility-gap",
        "Synthetic utility gap",
        "Difference between real-only and synthetic-supplemented holdout utility under the same evaluator.",
        "target",
        "task-metric",
        scope="scope.holdout",
    ),
)

GATES = (
    gate(
        NAMESPACE,
        "release",
        "Model release gate",
        "Reject deployment unless fixed quality, compatibility, policy, latency, and cost requirements pass.",
        (METRICS[0].id, METRICS[1].id, METRICS[2].id),
        oracle_kind="cross-implementation",
    ),
    gate(
        NAMESPACE,
        "rollback",
        "Rollback and monitoring gate",
        "Reject promotion when rollback cannot be verified or drift evidence cannot trigger a bounded response.",
        (METRICS[3].id, METRICS[4].id),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "synthetic-supplement",
        "Synthetic supplementation gate",
        "Escalate when synthetic data does not improve or preserve untouched real-data evidence across protected slices.",
        (METRICS[5].id,),
        oracle_kind="statistical",
        decision="escalate",
    ),
)

RECIPES = (
    recipe(
        NAMESPACE,
        "training-pipeline",
        "Reproducible training pipeline",
        "Freeze data and environment identities, train candidate routes, evaluate holdouts, package artifacts, and retain provenance.",
        ("artifact.validated-dataset",),
        ("artifact.evaluated-model",),
        ("ml.train", "ml.evaluate", "ml.package", "ml.provenance"),
        ("dag.learn", "dag.evaluate.model", "dag.govern.provenance"),
        ("template.kaggle-tabular", "template.deployment-release"),
        node_packs=(
            "example.data-science-lifecycle-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        design_packs=(
            "design-pack.tuning-search",
            "design-pack.evaluation-error",
            "design-pack.reproducibility-governance",
        ),
        examples=("ensemble-selection-and-stacking", "model-explainability-and-stability"),
        arena_tasks=(
            "arena.ensemble-selection-and-stacking",
            "arena.model-explainability-and-stability",
        ),
    ),
    recipe(
        NAMESPACE,
        "model-release",
        "Model serving and staged release",
        "Compile a tested model artifact into a versioned serving interface, staged rollout, health verification, and rollback plan.",
        ("artifact.evaluated-model",),
        ("artifact.deployed-model",),
        ("ml.package", "ml.serve", "ml.release", "ml.rollback"),
        ("dag.serve.api", "dag.serve.deploy", "dag.operate.observe"),
        ("template.deployment-release", "template.api-service"),
        node_packs=(
            "example.data-science-lifecycle-node-pack",
            "example.engineering-showcase-node-pack",
        ),
        design_packs=("design-pack.deployment-serving", "design-pack.monitoring-feedback"),
        examples=("model-release-monitoring-and-rollback",),
        arena_tasks=("arena.model-release-monitoring-and-rollback",),
        adapters=("adapter.openapi", "adapter.orchestrator.kubernetes"),
        limitations=(
            "The bundled adapters export manifests; they do not authenticate to or deploy into a production platform.",
        ),
    ),
    recipe(
        NAMESPACE,
        "model-monitoring",
        "Model monitoring and feedback",
        "Observe inputs, outputs, drift, delayed labels, SLOs, and rollback triggers without allowing telemetry to rewrite prior receipts.",
        ("artifact.deployed-model",),
        ("artifact.monitoring-evidence",),
        ("ml.observe", "ml.drift", "ml.feedback", "ml.recover"),
        ("dag.operate.observe", "dag.operate.incident", "dag.govern.provenance"),
        ("template.observability-sre", "template.deployment-release"),
        node_packs=("example.data-science-lifecycle-node-pack",),
        design_packs=("design-pack.monitoring-feedback", "design-pack.reproducibility-governance"),
        examples=("dataset-profiling-and-drift", "model-release-monitoring-and-rollback"),
        arena_tasks=(
            "arena.dataset-profiling-and-drift",
            "arena.model-release-monitoring-and-rollback",
        ),
        adapters=("adapter.orchestrator.dagster",),
    ),
    recipe(
        NAMESPACE,
        "synthetic-supplementation",
        "Synthetic data supplementation",
        "Generate, filter, compare, and mix synthetic records only when untouched real-data utility, privacy, and failure-slice gates pass.",
        ("artifact.validated-dataset",),
        ("artifact.validated-dataset",),
        ("synthetic.generate", "synthetic.filter", "synthetic.compare", "synthetic.mix"),
        ("dag.generate.synthetic.tabular", "dag.generate.augmentation", "dag.evaluate.model"),
        ("template.scientific-experiment",),
        node_packs=(
            "example.engineering-showcase-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        design_packs=("design-pack.synthetic-data", "design-pack.fairness-risk"),
        examples=("synthetic-tabular-augmentation",),
        arena_tasks=("arena.tabular-prediction",),
    ),
    recipe(
        NAMESPACE,
        "reinforcement-loop",
        "Bounded reinforcement-learning loop",
        "Freeze environment, reward, policy, safety, resource, and holdout boundaries before bounded policy improvement and promotion.",
        ("artifact.model-candidate",),
        ("artifact.evaluated-model",),
        ("rl.rollout", "rl.reward", "rl.update", "rl.evaluate", "rl.promote"),
        ("dag.learn.reinforcement", "dag.learn.optimize", "dag.evaluate.outer"),
        ("template.scientific-experiment",),
        node_packs=(
            "example.engineering-showcase-node-pack",
            "design-atlas.data-science-node-pack",
        ),
        design_packs=("design-pack.reinforcement-learning", "design-pack.robustness-stability"),
        examples=("reinforcement-learning-loop",),
        arena_tasks=("arena.scientific-experiment",),
    ),
)

PACK = specialized_pack(
    "ml_engineering",
    "ML engineering",
    "Reproducible training, synthetic supplementation, model packaging, serving, monitoring, reinforcement learning, and verified rollback.",
    domain_packs=("domain-pack.ai-ml", "domain-pack.platform-release", "domain-pack.sre-incident"),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "ml engineering",
        "mlops",
        "training pipeline",
        "model deployment",
        "model serving",
        "model monitoring",
        "drift",
        "rollback",
        "synthetic training data",
        "reinforcement learning",
        "rlhf",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)

__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
