"""Specialized capability pack for operations, reliability, and governance."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "operations"

FEATURES = (
    feature(
        NAMESPACE,
        "service-dependency-graph",
        "Service dependency graph",
        "Summarize upstream, downstream, regional, queue, database, and external-provider dependencies.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "slo-profile",
        "SLO profile",
        "Record service-level indicators, objectives, windows, burn policies, and missing telemetry.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "failure-history",
        "Failure history",
        "Summarize failure classes, recurrence, correlated dependencies, mitigations, and recovery evidence.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "authority-map",
        "Authority map",
        "Record owners, responders, approvers, credentials, effects, and separation-of-duty boundaries.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "recovery-readiness",
        "Recovery readiness",
        "Measure runbook, backup, checkpoint, rollback, compensation, and verification coverage.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "control-evidence-freshness",
        "Control-evidence freshness",
        "Measure evidence age, source identity, exceptions, owners, and renewal requirements.",
        "distribution",
    ),
    embedding_feature(
        NAMESPACE,
        "incident-profile-embedding",
        "Incident profile embedding",
        "Optional embedding of sanitized symptoms, topology, and failure history for retrieving comparable incidents in an exact space.",
    ),
)

METRICS = (
    metric(
        NAMESPACE,
        "slo-attainment",
        "SLO attainment",
        "Observed attainment of the declared service-level objective over its fixed window.",
        "maximize",
        "ratio",
        scope="scope.service",
    ),
    metric(
        NAMESPACE,
        "detection-time",
        "Detection time",
        "Time from fixed incident onset to an actionable independently recorded alert.",
        "minimize",
        "seconds",
        scope="scope.incident",
    ),
    metric(
        NAMESPACE,
        "recovery-time",
        "Recovery time",
        "Time from incident declaration to independently verified service recovery.",
        "minimize",
        "seconds",
        scope="scope.incident",
    ),
    metric(
        NAMESPACE,
        "recovery-success",
        "Recovery success",
        "Share of injected or observed incidents recovered within policy without undeclared effects.",
        "maximize",
        "ratio",
        scope="scope.incident",
    ),
    metric(
        NAMESPACE,
        "control-coverage",
        "Control coverage",
        "Share of required controls bound to current source, test, exception, owner, and review evidence.",
        "maximize",
        "ratio",
        scope="scope.governance",
    ),
    metric(
        NAMESPACE,
        "plan-feasibility",
        "Plan feasibility",
        "Share of proposed operational decisions satisfying all hard resource and policy constraints.",
        "maximize",
        "ratio",
        scope="scope.plan",
    ),
)

GATES = (
    gate(
        NAMESPACE,
        "service-health",
        "Service health gate",
        "Reject a recovery or rollout state that fails the declared SLO or independent health oracle.",
        (METRICS[0].id, METRICS[3].id),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "incident-response",
        "Incident response gate",
        "Escalate when detection or recovery exceeds policy, evidence is incomplete, or authority is unavailable.",
        (METRICS[1].id, METRICS[2].id),
        oracle_kind="human",
        decision="escalate",
    ),
    gate(
        NAMESPACE,
        "governed-plan",
        "Governed plan gate",
        "Reject operational plans that violate hard feasibility or required control-evidence boundaries.",
        (METRICS[4].id, METRICS[5].id),
        oracle_kind="external-authority",
    ),
)

RECIPES = (
    recipe(
        NAMESPACE,
        "observability",
        "Observability and SLO pipeline",
        "Define signals and SLOs, collect and correlate telemetry, detect symptoms, and preserve trace and lineage context.",
        ("artifact.deployed-service",),
        ("artifact.telemetry",),
        ("operations.instrument", "operations.correlate", "operations.slo", "operations.alert"),
        ("dag.operate.observe", "dag.govern.provenance"),
        ("template.observability-sre",),
        node_packs=("example.extended-arena-node-pack",),
        examples=("web-change-monitoring",),
        arena_tasks=("arena.sre-observability-response",),
        adapters=("adapter.orchestrator.dagster",),
    ),
    recipe(
        NAMESPACE,
        "incident-response",
        "Incident triage and verified recovery",
        "Gather scoped evidence, rank hypotheses, contain effects, recover through bounded actions, verify health, and retain learning evidence.",
        ("artifact.telemetry",),
        ("artifact.recovery-evidence",),
        (
            "incident.correlate",
            "incident.triage",
            "incident.contain",
            "incident.recover",
            "incident.verify",
        ),
        ("dag.operate.incident", "dag.human.review", "dag.evaluate.outer"),
        ("template.incident-response",),
        node_packs=("example.extended-arena-node-pack",),
        design_packs=("design-pack.monitoring-feedback", "design-pack.decision-handoff"),
        examples=("incident-triage",),
        arena_tasks=("arena.incident-triage",),
        adapters=("adapter.orchestrator.temporal",),
    ),
    recipe(
        NAMESPACE,
        "compliance-evidence",
        "Compliance and control evidence",
        "Bind controls to owners and source evidence, execute independent tests, preserve exceptions, and route attestation to authorized reviewers.",
        ("artifact.deployed-service",),
        ("artifact.control-evidence",),
        (
            "governance.map-control",
            "governance.collect-evidence",
            "governance.test",
            "governance.review",
        ),
        ("dag.govern.compliance", "dag.govern.provenance", "dag.human.review"),
        ("template.compliance-evidence",),
        node_packs=("design-atlas.data-science-node-pack",),
        design_packs=(
            "design-pack.fairness-risk",
            "design-pack.reproducibility-governance",
            "design-pack.decision-handoff",
        ),
        arena_tasks=("arena.compliance-evidence-pack",),
        limitations=(
            "A reference evidence graph is not a regulatory certification or external attestation.",
        ),
    ),
    recipe(
        NAMESPACE,
        "business-workflow",
        "Governed human and service workflow",
        "Establish identity and policy, gather records, calculate a decision, obtain required approval, perform effects, verify, notify, and archive.",
        ("artifact.decision-evidence",),
        ("artifact.operational-plan",),
        (
            "workflow.policy",
            "workflow.decide",
            "workflow.approve",
            "workflow.execute",
            "workflow.audit",
        ),
        ("dag.human.review", "dag.serve.backend", "dag.govern.provenance"),
        ("template.claims-processing", "template.customer-support"),
        node_packs=("reference.core-node-pack",),
        arena_tasks=("arena.claims-adjudication", "arena.api-business-workflow"),
        adapters=("adapter.bpmn", "adapter.orchestrator.temporal"),
    ),
    recipe(
        NAMESPACE,
        "planning-scheduling",
        "Supply-chain, planning, and scheduling",
        "Define variables, objectives, hard constraints, uncertainty scenarios, solver candidates, feasibility checks, and authorized release.",
        ("artifact.planning-inputs",),
        ("artifact.operational-plan",),
        (
            "planning.formulate",
            "planning.optimize",
            "planning.simulate",
            "planning.verify",
            "planning.release",
        ),
        ("dag.learn.optimize", "dag.evaluate.model", "dag.human.review"),
        ("template.supply-chain-planning", "template.optimization-scheduling"),
        node_packs=("example.extended-arena-node-pack",),
        design_packs=("design-pack.causality-experiments", "design-pack.decision-handoff"),
        arena_tasks=("arena.supply-chain-plan", "arena.constraint-scheduling"),
    ),
)

PACK = specialized_pack(
    "operations",
    "Operations and reliability",
    "Observability, SLOs, incident response, recovery, compliance evidence, governed workflows, and constrained operational planning.",
    domain_packs=(
        "domain-pack.sre-incident",
        "domain-pack.security-compliance",
        "domain-pack.business-human-workflow",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "operations",
        "sre",
        "observability",
        "slo",
        "incident",
        "on call",
        "recovery",
        "runbook",
        "compliance",
        "audit",
        "business workflow",
        "supply chain",
        "scheduling",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)

__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
