"""Specialized package for privacy engineering, governance, and compliance evidence."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "privacy-governance-compliance"
FEATURES = (
    feature(
        NAMESPACE,
        "data-map",
        "Data map",
        "Profile data classes, subjects, systems, flows, purposes, consent, retention, residency, recipients, and owners.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "control-coverage",
        "Control coverage",
        "Map requirements to controls, owners, systems, test procedures, evidence, exceptions, and compensating controls.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "privacy-risk",
        "Privacy risk",
        "Measure direct identifiers, quasi-identifiers, sensitive attributes, linkability, leakage paths, and consequence.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "requirement-embedding",
        "Requirement and control embedding",
        "Optional version-bound requirement/control embedding for discovery under an exact space identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "prohibited-leakage",
        "Prohibited leakage",
        "Residual prohibited identifiers, attributes, secrets, or unapproved disclosures.",
        "minimize",
        "count",
        scope="scope.release",
    ),
    metric(
        NAMESPACE,
        "control-coverage",
        "Control coverage",
        "Applicable requirements with tested controls and authenticated evidence.",
        "maximize",
        "ratio",
        scope="scope.control",
    ),
    metric(
        NAMESPACE,
        "exception-aging",
        "Exception aging",
        "Open material exceptions beyond the declared remediation deadline.",
        "minimize",
        "count",
        scope="scope.exception",
    ),
    metric(
        NAMESPACE,
        "evidence-integrity",
        "Evidence integrity",
        "Control conclusions with exact source, period, population, sample, test, reviewer, and receipt identity.",
        "maximize",
        "ratio",
        scope="scope.evidence",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "privacy-release",
        "Privacy release gate",
        "Reject release when purpose, authority, minimization, retention, or leakage checks fail.",
        (METRICS[0].id,),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "attestation",
        "Compliance attestation gate",
        "Escalate material attestations without complete control coverage, evidence integrity, exception disclosure, and accountable approval.",
        (METRICS[1].id, METRICS[2].id, METRICS[3].id),
        oracle_kind="human",
        decision="escalate",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "privacy-design",
        "Privacy-by-design data flow",
        "Map data and purposes, minimize collection, enforce purpose and retention boundaries, model threats, and define independent release checks.",
        ("artifact.system-inventory",),
        ("artifact.privacy-design",),
        (
            "privacy.data-map",
            "privacy.purpose",
            "privacy.minimize",
            "privacy.threat-model",
            "privacy.retention",
        ),
        ("dag.govern.privacy", "dag.govern.security", "dag.generate.report"),
        ("template.compliance-evidence", "template.login-system"),
        design_packs=("design-pack.fairness-risk", "design-pack.reproducibility-governance"),
        arena_tasks=("arena.compliance-evidence-pack",),
    ),
    recipe(
        NAMESPACE,
        "deidentify",
        "De-identification and leakage assurance",
        "Detect sensitive values and relationships, apply a declared transformation, measure utility and linkability, and independently scan output leakage.",
        ("artifact.sensitive-dataset",),
        ("artifact.governed-dataset",),
        (
            "privacy.detect",
            "privacy.transform",
            "privacy.linkability",
            "privacy.utility",
            "privacy.leakage-check",
        ),
        ("dag.govern.privacy", "dag.prepare.clean", "dag.evaluate.data", "dag.evaluate.safety"),
        ("template.document-intelligence", "template.compliance-evidence"),
        node_packs=("example.extended-arena-node-pack",),
        question_packs=("question-pack.generic-tabular", "question-pack.document"),
        examples=("pii-redaction",),
        arena_tasks=("arena.pii-redaction",),
        limitations=(
            "Fixture redaction is not a formal anonymity or re-identification-risk guarantee.",
        ),
    ),
    recipe(
        NAMESPACE,
        "control-evidence",
        "Compliance control evidence",
        "Map exact requirements, collect authenticated evidence, test design and operation, manage exceptions, verify remediation, and publish bounded attestation evidence.",
        ("artifact.requirement-set",),
        ("artifact.control-evidence",),
        (
            "compliance.map",
            "compliance.collect",
            "compliance.test",
            "compliance.exception",
            "compliance.attest",
        ),
        ("dag.govern.compliance", "dag.govern.provenance", "dag.human.review"),
        ("template.compliance-evidence",),
        design_packs=("design-pack.reproducibility-governance", "design-pack.decision-handoff"),
        arena_tasks=("arena.compliance-evidence-pack",),
    ),
)
PACK = specialized_pack(
    "privacy_governance_compliance",
    "Privacy, governance, and compliance",
    "Privacy-by-design, de-identification, data governance, control testing, exception management, audit evidence, and bounded attestations.",
    domain_packs=(
        "domain-pack.security-compliance",
        "domain-pack.data-integration",
        "domain-pack.business-human-workflow",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "privacy",
        "governance",
        "compliance",
        "audit",
        "control",
        "pii",
        "redaction",
        "deidentification",
        "retention",
        "consent",
        "attestation",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
