"""Specialized package for product analytics, experimentation, and feedback loops."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "product-experimentation"
FEATURES = (
    feature(
        NAMESPACE,
        "event-contract",
        "Product event contract",
        "Profile actors, sessions, entities, event time, exposure, assignment, identity stitching, consent, and schema versions.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "experiment-design",
        "Experiment design",
        "Profile unit, population, hypothesis, variants, randomization, interference, duration, power, outcomes, and guardrails.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "journey-shape",
        "Journey and funnel shape",
        "Measure paths, loops, drop-off, latency, retention, cohorts, channels, devices, and segment imbalance.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "hypothesis-embedding",
        "Product hypothesis embedding",
        "Optional redacted hypothesis and behavior embedding for historical discovery under an exact space identity.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "event-validity",
        "Event validity",
        "Events satisfying identity, schema, time, consent, deduplication, and exposure semantics.",
        "maximize",
        "ratio",
        scope="scope.event",
    ),
    metric(
        NAMESPACE,
        "primary-effect",
        "Primary treatment effect",
        "Predeclared effect and uncertainty for the primary outcome under the frozen analysis contract.",
        "maximize",
        "effect",
        scope="scope.experiment",
    ),
    metric(
        NAMESPACE,
        "guardrail-regression",
        "Guardrail regressions",
        "Statistically and operationally material adverse movement in predeclared guardrails.",
        "minimize",
        "count",
        scope="scope.guardrail",
    ),
    metric(
        NAMESPACE,
        "decision-reproducibility",
        "Decision reproducibility",
        "Experiment decisions reproducible from exact assignment, data, exclusions, estimator, and correction identity.",
        "maximize",
        "ratio",
        scope="scope.decision",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "instrumentation",
        "Product instrumentation gate",
        "Reject behavioral conclusions when event, identity, assignment, exposure, or consent contracts fail.",
        (METRICS[0].id,),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "decision",
        "Experiment decision gate",
        "Reject ship, stop, or iterate claims without frozen outcomes, uncertainty, guardrails, multiplicity policy, and reproducible evidence.",
        (METRICS[1].id, METRICS[2].id, METRICS[3].id),
        oracle_kind="statistical",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "instrument",
        "Product event instrumentation",
        "Define semantic events, validate client and server emissions, reconcile identity and exposure, monitor schema drift, and publish event quality evidence.",
        ("artifact.product-event-spec",),
        ("artifact.validated-product-events",),
        (
            "product.event-contract",
            "product.instrument",
            "product.reconcile-identity",
            "product.validate",
            "product.monitor",
        ),
        ("dag.acquire.stream", "dag.prepare.schema", "dag.prepare.verify", "dag.operate.observe"),
        ("template.product-experimentation", "template.event-driven-system"),
        node_packs=("example.engineering-showcase-node-pack",),
        question_packs=("question-pack.person", "question-pack.datetime"),
        examples=("event-time-windowing",),
        arena_tasks=("arena.product-experimentation",),
    ),
    recipe(
        NAMESPACE,
        "journeys",
        "User journey and funnel modeling",
        "Sessionize under explicit rules, derive journeys and funnels, preserve alternate paths, segment behavior, and test stability across definitions.",
        ("artifact.validated-product-events",),
        ("artifact.product-journey-report",),
        (
            "product.sessionize",
            "product.journey",
            "product.funnel",
            "product.segment",
            "product.sensitivity",
        ),
        (
            "dag.integrate.enrich.temporal",
            "dag.learn.cluster",
            "dag.evaluate.metamorphic",
            "dag.generate.report",
        ),
        ("template.product-experimentation",),
        node_packs=("example.engineering-showcase-node-pack",),
        examples=("user-journey-modeling",),
        arena_tasks=("arena.product-experimentation",),
    ),
    recipe(
        NAMESPACE,
        "experiment",
        "Controlled product experiment",
        "Freeze hypothesis and estimand, validate randomization and exposure, analyze primary and guardrail outcomes, inspect heterogeneity, and publish a bounded decision.",
        ("artifact.product-experiment",),
        ("artifact.product-experiment-report",),
        (
            "product.freeze-design",
            "product.validate-randomization",
            "product.estimate",
            "product.guardrails",
            "product.heterogeneity",
            "product.decide",
        ),
        ("dag.learn.causal", "dag.evaluate.model", "dag.human.review", "dag.govern.provenance"),
        ("template.product-experimentation", "template.scientific-experiment"),
        design_packs=(
            "design-pack.causality-experiments",
            "design-pack.validation-splits",
            "design-pack.decision-handoff",
        ),
        arena_tasks=("arena.product-experimentation",),
    ),
)
PACK = specialized_pack(
    "product_experimentation",
    "Product experimentation",
    "Product-event contracts, journey and funnel analytics, controlled experiments, guardrails, causal evidence, decisions, and monitoring.",
    domain_packs=(
        "domain-pack.event-stream",
        "domain-pack.data-integration",
        "domain-pack.science-optimization",
        "domain-pack.business-human-workflow",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "product analytics",
        "ab test",
        "a/b test",
        "experiment",
        "user journey",
        "funnel",
        "retention",
        "conversion",
        "feature flag",
        "telemetry",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
