"""Specialized package for search, retrieval, ranking, and recommendation systems."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "search-recommendation"
FEATURES = (
    feature(
        NAMESPACE,
        "corpus-catalog",
        "Corpus and catalog",
        "Profile documents or items, fields, languages, freshness, permissions, duplicates, taxonomy, inventory, and provenance.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "query-user-context",
        "Query and user context",
        "Profile intents, sessions, histories, cold start, locale, device, eligibility, privacy, and personalization boundaries.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "ranking-surface",
        "Retrieval and ranking surface",
        "Measure candidate generators, rankers, filters, diversity, latency, feedback bias, exposure, and failure slices.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "semantic-embedding",
        "Retrieval-space embedding",
        "Optional query/item embedding for retrieval only when exact model, revision, preprocessing, dimension, and distance identity match.",
    ),
)
METRICS = (
    metric(
        NAMESPACE,
        "relevance",
        "Ranking relevance",
        "Task-appropriate recall, precision, gain, rank, or satisfaction on fixed query and user slices.",
        "maximize",
        "score",
        scope="scope.query",
    ),
    metric(
        NAMESPACE,
        "coverage-diversity",
        "Coverage and diversity",
        "Eligible catalog, intent, supplier, topic, or viewpoint coverage under declared diversity constraints.",
        "maximize",
        "score",
        scope="scope.ranking",
    ),
    metric(
        NAMESPACE,
        "unsafe-ineligible",
        "Unsafe or ineligible results",
        "Permission, policy, inventory, privacy, factuality, or eligibility violations shown to a user.",
        "minimize",
        "count",
        scope="scope.result",
    ),
    metric(
        NAMESPACE,
        "latency",
        "Serving latency",
        "End-to-end retrieval, filtering, ranking, and rendering latency at the declared percentile.",
        "minimize",
        "milliseconds",
        scope="scope.request",
    ),
)
GATES = (
    gate(
        NAMESPACE,
        "eligibility",
        "Search eligibility gate",
        "Reject rankings containing unauthorized, unsafe, unavailable, stale, or otherwise ineligible results.",
        (METRICS[2].id,),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "quality",
        "Search quality gate",
        "Reject promotion without fixed-slice relevance, coverage, diversity, latency, and regression evidence.",
        (METRICS[0].id, METRICS[1].id, METRICS[3].id),
        oracle_kind="cross-implementation",
    ),
)
RECIPES = (
    recipe(
        NAMESPACE,
        "index",
        "Permission-aware search index",
        "Parse and normalize content, resolve identity and access, chunk with provenance, build lexical and semantic indexes, and validate freshness and deletion.",
        ("artifact.search-corpus",),
        ("artifact.search-index",),
        (
            "search.parse",
            "search.identity",
            "search.permissions",
            "search.chunk",
            "search.index",
            "search.validate",
        ),
        (
            "dag.acquire.document",
            "dag.prepare.parse",
            "dag.integrate.enrich.knowledge",
            "dag.govern.privacy",
        ),
        ("template.knowledge-retrieval",),
        node_packs=("example.engineering-showcase-node-pack",),
        question_packs=("question-pack.document",),
        design_packs=("design-pack.text-document",),
        examples=("grounded-document-extraction",),
        arena_tasks=("arena.grounded-knowledge-system",),
    ),
    recipe(
        NAMESPACE,
        "retrieve-rank",
        "Hybrid retrieve and rank",
        "Interpret intent, generate lexical, semantic and structured candidates, enforce eligibility, rank, diversify, explain, and measure fixed query slices.",
        ("artifact.search-request",),
        ("artifact.ranked-results",),
        (
            "search.intent",
            "search.retrieve",
            "search.filter",
            "search.rank",
            "search.diversify",
            "search.explain",
        ),
        (
            "dag.integrate.enrich.knowledge",
            "dag.learn.ranking",
            "dag.evaluate.model",
            "dag.serve.api",
        ),
        ("template.knowledge-retrieval", "template.recommendation-ranking"),
        node_packs=("example.extended-arena-node-pack",),
        examples=("recommendation-ranking",),
        arena_tasks=("arena.recommendation-ranking", "arena.grounded-knowledge-system"),
    ),
    recipe(
        NAMESPACE,
        "recommend",
        "Recommendation feedback loop",
        "Build consented features, generate and filter candidates, rank with exploration bounds, evaluate counterfactual limitations, monitor feedback bias, and retain rollback.",
        ("artifact.recommendation-events",),
        ("artifact.recommendation-policy",),
        (
            "recommend.feature",
            "recommend.candidate",
            "recommend.rank",
            "recommend.explore",
            "recommend.evaluate",
            "recommend.monitor",
        ),
        (
            "dag.learn.ranking",
            "dag.learn.reinforcement",
            "dag.evaluate.model",
            "dag.operate.observe",
        ),
        ("template.recommendation-ranking", "template.product-experimentation"),
        node_packs=("example.extended-arena-node-pack",),
        design_packs=(
            "design-pack.reinforcement-learning",
            "design-pack.fairness-risk",
            "design-pack.monitoring-feedback",
        ),
        examples=("recommendation-ranking",),
        arena_tasks=("arena.recommendation-ranking",),
        limitations=(
            "Logged feedback is exposure-biased; offline uplift does not establish causal online benefit.",
        ),
    ),
)
PACK = specialized_pack(
    "search_recommendation",
    "Search and recommendation",
    "Corpus and catalog preparation, permission-aware indexing, hybrid retrieval, ranking, recommendation, evaluation, serving, and feedback-bias control.",
    domain_packs=(
        "domain-pack.data-integration",
        "domain-pack.ai-ml",
        "domain-pack.llm-agent",
        "domain-pack.backend-api",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "search",
        "retrieval",
        "ranking",
        "recommendation",
        "recommender",
        "semantic search",
        "vector search",
        "rag",
        "catalog",
        "personalization",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)
__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
