"""Specialized capability pack for repository, service, and release engineering."""

from solutiongraph.specialized._builders import (
    embedding_feature,
    feature,
    gate,
    metric,
    recipe,
    specialized_pack,
)

NAMESPACE = "software-engineering"

FEATURES = (
    feature(
        NAMESPACE,
        "repository-shape",
        "Repository shape",
        "Count languages, modules, dependency boundaries, generated assets, tests, and build surfaces.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "change-surface",
        "Change surface",
        "Summarize affected interfaces, callers, migrations, tests, documentation, and operational dependencies.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "test-topology",
        "Test topology",
        "Measure unit, property, integration, end-to-end, regression, mutation, and sealed-case coverage.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "dependency-risk",
        "Dependency risk",
        "Summarize version constraints, provenance, licenses, vulnerabilities, native builds, and update depth.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "api-compatibility",
        "API compatibility",
        "Compare request, response, event, schema, persistence, and client contracts with the baseline.",
        "mapping",
    ),
    feature(
        NAMESPACE,
        "release-blast-radius",
        "Release blast radius",
        "Estimate users, services, data, regions, and irreversible effects touched by a release.",
        "mapping",
    ),
    embedding_feature(
        NAMESPACE,
        "ticket-repository-embedding",
        "Ticket and repository embedding",
        "Optional embedding of the ticket, interfaces, and redacted repository profile for retrieving similar verified changes.",
    ),
)

METRICS = (
    metric(
        NAMESPACE,
        "acceptance-pass-rate",
        "Acceptance pass rate",
        "Share of fixed functional, property, integration, and sealed acceptance cases passing.",
        "maximize",
        "ratio",
        scope="scope.change",
    ),
    metric(
        NAMESPACE,
        "regression-rate",
        "Regression rate",
        "Share of protected baseline behavior changed outside the task contract.",
        "minimize",
        "ratio",
        scope="scope.change",
    ),
    metric(
        NAMESPACE,
        "compatibility-violations",
        "Compatibility violations",
        "Count of independently detected interface or migration compatibility violations.",
        "minimize",
        "count",
        scope="scope.release",
    ),
    metric(
        NAMESPACE,
        "change-complexity",
        "Change complexity",
        "Reviewable size and structural complexity retained as a separate objective.",
        "minimize",
        "complexity-unit",
        scope="scope.change",
    ),
    metric(
        NAMESPACE,
        "release-recovery",
        "Release recovery",
        "Observed time and success rate for rollback or compensation under injected failure.",
        "minimize",
        "seconds",
        scope="scope.recovery",
    ),
    metric(
        NAMESPACE,
        "supply-chain-coverage",
        "Supply-chain coverage",
        "Share of shipped artifacts bound to exact source, dependency, build, and attestation identities.",
        "maximize",
        "ratio",
        scope="scope.release",
    ),
)

GATES = (
    gate(
        NAMESPACE,
        "change-acceptance",
        "Change acceptance gate",
        "Reject a change that fails fixed acceptance, regression, compatibility, or scope constraints.",
        (METRICS[0].id, METRICS[1].id, METRICS[2].id),
        oracle_kind="property",
    ),
    gate(
        NAMESPACE,
        "release-assurance",
        "Release assurance gate",
        "Reject release when rollback evidence or supply-chain identity is incomplete.",
        (METRICS[4].id, METRICS[5].id),
        oracle_kind="cross-implementation",
    ),
)

RECIPES = (
    recipe(
        NAMESPACE,
        "repository-repair",
        "Repository diagnosis and repair",
        "Localize the failure, define protected behavior, implement a bounded change, run layered checks, and emit reviewable evidence.",
        ("artifact.repository",),
        ("artifact.verified-change",),
        ("software.diagnose", "software.change", "software.test", "software.review"),
        ("dag.evaluate.regression", "dag.evaluate.metamorphic", "dag.serve.backend"),
        ("template.qa-engineering",),
        node_packs=("example.real-world-node-pack", "example.extended-arena-node-pack"),
        design_packs=(
            "design-pack.task-contract",
            "design-pack.evaluation-error",
            "design-pack.reproducibility-governance",
        ),
        examples=("tested-code-repair",),
        arena_tasks=("arena.repository-repair",),
        agent_benchmarks=("agent-benchmark.reference-smoke",),
    ),
    recipe(
        NAMESPACE,
        "release-pipeline",
        "Build, verify, and stage a release",
        "Produce a reproducible artifact, bind provenance, execute compatibility and security gates, stage rollout, and retain rollback.",
        ("artifact.verified-change",),
        ("artifact.release-candidate",),
        ("software.build", "software.assure", "software.release", "software.rollback"),
        ("dag.serve.deploy", "dag.govern.security", "dag.govern.provenance"),
        ("template.deployment-release",),
        node_packs=("example.extended-arena-node-pack", "example.engineering-showcase-node-pack"),
        examples=("dependency-assurance", "frontend-release-journey"),
        arena_tasks=("arena.dependency-assurance", "arena.deployment-release"),
        adapters=("adapter.orchestrator.kubernetes",),
    ),
    recipe(
        NAMESPACE,
        "backend-service",
        "Contract-safe backend service",
        "Model request validation, domain behavior, idempotent effects, persistence, observability, and compensation behind a stable API.",
        ("artifact.release-candidate",),
        ("artifact.deployed-service",),
        (
            "service.contract",
            "service.execute",
            "service.persist",
            "service.observe",
            "service.recover",
        ),
        ("dag.serve.api", "dag.serve.backend", "dag.operate.observe"),
        ("template.api-service",),
        node_packs=("example.engineering-showcase-node-pack",),
        examples=("idempotent-api-contract",),
        arena_tasks=("arena.idempotent-api-contract",),
        adapters=("adapter.openapi", "adapter.orchestrator.temporal"),
        limitations=(
            "Reference adapters project contracts and plans but do not host an authenticated production service.",
        ),
    ),
    recipe(
        NAMESPACE,
        "frontend-journey",
        "Frontend journey and release assurance",
        "Compile critical journeys, render and interaction checks, accessibility evidence, staged release, and independent effect verification.",
        ("artifact.release-candidate",),
        ("artifact.deployed-service",),
        (
            "frontend.journey",
            "frontend.render",
            "frontend.accessibility",
            "frontend.verify",
            "frontend.release",
        ),
        ("dag.serve.frontend", "dag.serve.automation", "dag.evaluate.regression"),
        ("template.qa-engineering", "template.web-automation"),
        node_packs=("example.engineering-showcase-node-pack",),
        examples=("frontend-release-journey",),
        arena_tasks=("arena.frontend-release-journey",),
    ),
    recipe(
        NAMESPACE,
        "database-migration",
        "Database migration and cutover",
        "Inventory schema and dependencies, convert and backfill, run CDC, reconcile, cut over, verify, and preserve rollback.",
        ("artifact.database-state",),
        ("artifact.migrated-database",),
        (
            "database.inventory",
            "database.convert",
            "database.backfill",
            "database.reconcile",
            "database.cutover",
        ),
        ("dag.operate.migrate", "dag.integrate.reconcile", "dag.evaluate.data"),
        ("template.database-migration",),
        node_packs=("example.extended-arena-node-pack",),
        examples=("schema-migration",),
        arena_tasks=("arena.database-migration", "arena.schema-migration"),
        adapters=("adapter.orchestrator.temporal",),
    ),
)

PACK = specialized_pack(
    "software_engineering",
    "Software engineering",
    "Repository repair, testing, API/backend systems, frontend journeys, database migrations, supply-chain assurance, and staged releases.",
    domain_packs=(
        "domain-pack.backend-api",
        "domain-pack.frontend-browser",
        "domain-pack.platform-release",
        "domain-pack.database-storage",
    ),
    categories=tuple(dict.fromkeys(category for item in RECIPES for category in item.category_ids)),
    signals=(
        "software engineering",
        "repository repair",
        "bug fix",
        "regression test",
        "backend",
        "api",
        "frontend",
        "database migration",
        "release pipeline",
        "deployment",
        "dependency assurance",
    ),
    recipes=RECIPES,
    features=FEATURES,
    metrics=METRICS,
    gates=GATES,
)

__all__ = ["FEATURES", "GATES", "METRICS", "PACK", "RECIPES"]
