"""Reference semantic concepts used by the built-in interrogation packs."""

from __future__ import annotations

from solutiongraph.interrogation.model import (
    ConceptDefinition,
    StandardsReference,
)

SCHEMA_ORG = StandardsReference(
    "reference.schema-org",
    "https://schema.org/",
    "reference.semantic-vocabulary",
    revision="current-web",
    license="CC-BY-SA",
)
USPS_PUB28 = StandardsReference(
    "reference.usps-publication-28",
    "https://pe.usps.com/text/pub28/welcome.htm",
    "reference.address-normalization",
    revision="2024-10",
    jurisdiction="US",
)
CENSUS_GEOCODER = StandardsReference(
    "reference.census-geocoder",
    "https://www.census.gov/programs-surveys/geography/technical-documentation/complete-technical-documentation/census-geocoder.html",
    "reference.geographic-evidence",
    jurisdiction="US",
    notes="Range and geography evidence; not proof of deliverability or structure existence.",
)
GLEIF = StandardsReference(
    "reference.gleif-api",
    "https://www.gleif.org/en/lei-data/gleif-api",
    "reference.entity-authority",
    notes="Authoritative for LEI-covered entities only.",
)
RFC5322 = StandardsReference(
    "reference.rfc-5322",
    "https://datatracker.ietf.org/doc/html/rfc5322",
    "reference.email-syntax",
)
E164 = StandardsReference(
    "reference.itu-e164",
    "https://www.itu.int/rec/T-REC-E.164/",
    "reference.telephone-numbering",
)
SHACL = StandardsReference(
    "reference.w3c-shacl",
    "https://www.w3.org/TR/shacl/",
    "reference.constraint-language",
)
DQV = StandardsReference(
    "reference.w3c-dqv",
    "https://www.w3.org/TR/vocab-dqv/",
    "reference.quality-vocabulary",
)


def _concept(
    concept_id: str,
    uri: str,
    label: str,
    value_type: str,
    aliases: tuple[str, ...],
    *,
    parents: tuple[str, ...] = (),
    references: tuple[StandardsReference, ...] = (SCHEMA_ORG,),
    description: str = "",
) -> ConceptDefinition:
    return ConceptDefinition(
        id=concept_id,
        version="1.0.0",
        canonical_uri=uri,
        label=label,
        value_type=value_type,
        aliases=aliases,
        description=description,
        parent_ids=parents,
        references=references,
    )


REFERENCE_CONCEPTS = (
    _concept(
        "concept.dataset.recordset",
        "urn:solutiongraph:concept:dataset-recordset",
        "Tabular record set",
        "data.recordset",
        ("dataset", "records", "rows", "table"),
        references=(DQV, SHACL),
    ),
    _concept(
        "concept.dataset.source",
        "urn:solutiongraph:concept:data-source",
        "Data source",
        "data.source-id",
        ("source", "source_system", "system_of_record", "origin"),
        references=(DQV,),
    ),
    _concept(
        "concept.dataset.record-id",
        "https://schema.org/identifier",
        "Record identifier",
        "data.identifier",
        ("id", "record_id", "row_id", "identifier", "uuid"),
    ),
    _concept(
        "concept.organization.entity",
        "https://schema.org/Organization",
        "Organization",
        "entity.organization",
        ("organization", "company", "business", "employer", "vendor"),
    ),
    _concept(
        "concept.organization.name",
        "https://schema.org/name",
        "Organization display name",
        "text.organization-name",
        ("company_name", "organization_name", "business_name", "vendor_name", "employer_name"),
        parents=("concept.organization.entity",),
    ),
    _concept(
        "concept.organization.legal-name",
        "https://schema.org/legalName",
        "Organization legal name",
        "text.organization-legal-name",
        ("legal_name", "registered_name", "official_company_name", "entity_legal_name"),
        parents=("concept.organization.name",),
    ),
    _concept(
        "concept.organization.alternate-name",
        "https://schema.org/alternateName",
        "Organization alternate or brand name",
        "text.organization-alternate-name",
        ("brand_name", "dba", "trade_name", "alternate_name", "former_name"),
        parents=("concept.organization.name",),
    ),
    _concept(
        "concept.organization.identifier",
        "https://schema.org/identifier",
        "Organization identifier",
        "data.organization-identifier",
        ("company_id", "organization_id", "lei", "tax_id", "registration_number"),
        parents=("concept.organization.entity",),
        references=(SCHEMA_ORG, GLEIF),
    ),
    _concept(
        "concept.organization.domain",
        "https://schema.org/url",
        "Organization web domain",
        "text.domain",
        ("domain", "website", "company_url", "organization_url", "homepage"),
        parents=("concept.organization.entity",),
    ),
    _concept(
        "concept.organization.status-date",
        "https://schema.org/dissolutionDate",
        "Organization status date",
        "time.date",
        ("dissolution_date", "incorporation_date", "registration_date", "effective_date"),
        parents=("concept.organization.entity",),
    ),
    _concept(
        "concept.postal.address",
        "https://schema.org/PostalAddress",
        "Postal address",
        "geo.postal-address",
        ("address", "postal_address", "mailing_address", "legal_address", "registered_address"),
    ),
    _concept(
        "concept.postal.street",
        "https://schema.org/streetAddress",
        "Street address",
        "text.street-address",
        ("street", "street_address", "address_line_1", "address1", "address_line1"),
        parents=("concept.postal.address",),
        references=(SCHEMA_ORG, USPS_PUB28),
    ),
    _concept(
        "concept.postal.unit",
        "https://schema.org/extendedAddress",
        "Secondary address unit",
        "text.address-unit",
        ("unit", "suite", "apartment", "apt", "address_line_2", "address2"),
        parents=("concept.postal.address",),
        references=(SCHEMA_ORG, USPS_PUB28),
    ),
    _concept(
        "concept.postal.city",
        "https://schema.org/addressLocality",
        "Address locality or city",
        "geo.locality",
        ("city", "locality", "town", "municipality", "address_city"),
        parents=("concept.postal.address",),
    ),
    _concept(
        "concept.postal.region",
        "https://schema.org/addressRegion",
        "Address region or state",
        "geo.region",
        ("state", "region", "province", "state_code", "address_state"),
        parents=("concept.postal.address",),
    ),
    _concept(
        "concept.postal.code",
        "https://schema.org/postalCode",
        "Postal code",
        "geo.postal-code",
        ("zip", "zipcode", "zip_code", "postal_code", "postcode"),
        parents=("concept.postal.address",),
    ),
    _concept(
        "concept.postal.country",
        "https://schema.org/addressCountry",
        "Address country",
        "geo.country",
        ("country", "country_code", "address_country", "iso_country"),
        parents=("concept.postal.address",),
    ),
    _concept(
        "concept.geography.county",
        "urn:solutiongraph:concept:county",
        "County or equivalent subdivision",
        "geo.county",
        ("county", "county_name", "county_fips", "fips"),
        references=(CENSUS_GEOCODER,),
    ),
    _concept(
        "concept.geography.latitude",
        "https://schema.org/latitude",
        "Latitude",
        "geo.latitude",
        ("latitude", "lat", "y_coordinate"),
    ),
    _concept(
        "concept.geography.longitude",
        "https://schema.org/longitude",
        "Longitude",
        "geo.longitude",
        ("longitude", "lon", "lng", "x_coordinate"),
    ),
    _concept(
        "concept.geography.vintage",
        "urn:solutiongraph:concept:geography-vintage",
        "Geographic reference vintage",
        "time.reference-vintage",
        ("geography_vintage", "boundary_year", "fips_vintage", "tiger_year"),
        references=(CENSUS_GEOCODER,),
    ),
    _concept(
        "concept.contact.email",
        "https://schema.org/email",
        "Email address",
        "contact.email",
        ("email", "email_address", "contact_email", "work_email"),
        references=(SCHEMA_ORG, RFC5322),
    ),
    _concept(
        "concept.contact.telephone",
        "https://schema.org/telephone",
        "Telephone number",
        "contact.telephone",
        ("phone", "telephone", "phone_number", "mobile", "contact_phone"),
        references=(SCHEMA_ORG, E164),
    ),
    _concept(
        "concept.contact.type",
        "https://schema.org/contactType",
        "Contact point type",
        "contact.type",
        ("contact_type", "phone_type", "email_type", "department"),
    ),
    _concept(
        "concept.contact.language",
        "https://schema.org/availableLanguage",
        "Available contact language",
        "language.code",
        ("language", "preferred_language", "available_language", "locale"),
    ),
    _concept(
        "concept.person.name",
        "https://schema.org/name",
        "Person name",
        "text.person-name",
        ("person_name", "full_name", "contact_name", "customer_name"),
    ),
    _concept(
        "concept.person.given-name",
        "https://schema.org/givenName",
        "Given name",
        "text.given-name",
        ("first_name", "given_name", "forename"),
        parents=("concept.person.name",),
    ),
    _concept(
        "concept.person.family-name",
        "https://schema.org/familyName",
        "Family name",
        "text.family-name",
        ("last_name", "family_name", "surname"),
        parents=("concept.person.name",),
    ),
    _concept(
        "concept.time.instant",
        "https://schema.org/DateTime",
        "Date-time instant",
        "time.datetime",
        ("timestamp", "datetime", "created_at", "updated_at", "event_time"),
    ),
    _concept(
        "concept.time.date",
        "https://schema.org/Date",
        "Calendar date",
        "time.date",
        ("date", "event_date", "effective_date", "as_of_date"),
    ),
    _concept(
        "concept.time.start",
        "https://schema.org/startDate",
        "Start date-time",
        "time.datetime",
        ("start", "start_date", "start_time", "valid_from"),
    ),
    _concept(
        "concept.time.end",
        "https://schema.org/endDate",
        "End date-time",
        "time.datetime",
        ("end", "end_date", "end_time", "valid_to"),
    ),
    _concept(
        "concept.time.timezone",
        "urn:solutiongraph:concept:timezone",
        "Timezone",
        "time.timezone",
        ("timezone", "time_zone", "tz", "utc_offset"),
        references=(),
    ),
    _concept(
        "concept.product.name",
        "https://schema.org/name",
        "Product name",
        "text.product-name",
        ("product_name", "item_name", "sku_name", "title"),
    ),
    _concept(
        "concept.product.identifier",
        "https://schema.org/productID",
        "Product identifier",
        "data.product-identifier",
        ("product_id", "sku", "gtin", "upc", "ean", "item_id"),
    ),
    _concept(
        "concept.product.brand",
        "https://schema.org/brand",
        "Product brand",
        "text.brand",
        ("brand", "brand_name", "manufacturer"),
    ),
    _concept(
        "concept.transaction.id",
        "https://schema.org/identifier",
        "Transaction identifier",
        "data.transaction-identifier",
        ("transaction_id", "invoice_id", "order_id", "payment_id"),
    ),
    _concept(
        "concept.transaction.amount",
        "https://schema.org/price",
        "Monetary amount",
        "money.amount",
        ("amount", "price", "total", "subtotal", "invoice_amount"),
    ),
    _concept(
        "concept.transaction.currency",
        "https://schema.org/priceCurrency",
        "Currency code",
        "money.currency",
        ("currency", "currency_code", "price_currency"),
    ),
    _concept(
        "concept.transaction.status",
        "https://schema.org/paymentStatus",
        "Transaction status",
        "transaction.status",
        ("status", "payment_status", "order_status", "invoice_status"),
    ),
    _concept(
        "concept.document.identifier",
        "https://schema.org/identifier",
        "Document identifier",
        "data.document-identifier",
        ("document_id", "file_id", "doc_id", "case_id"),
    ),
    _concept(
        "concept.document.text",
        "https://schema.org/text",
        "Document text",
        "text.document",
        ("text", "document_text", "content", "body", "ocr_text"),
    ),
    _concept(
        "concept.document.url",
        "https://schema.org/contentUrl",
        "Document URL",
        "text.url",
        ("url", "document_url", "file_url", "source_url"),
    ),
    _concept(
        "concept.ml.target",
        "urn:solutiongraph:concept:ml-target",
        "Machine-learning target",
        "ml.target",
        ("target", "label", "y", "outcome", "response"),
        references=(DQV,),
    ),
    _concept(
        "concept.ml.split",
        "urn:solutiongraph:concept:ml-split",
        "Dataset split",
        "ml.split",
        ("split", "fold", "partition", "train_test", "cv_fold"),
        references=(DQV,),
    ),
    _concept(
        "concept.ml.prediction",
        "urn:solutiongraph:concept:ml-prediction",
        "Model prediction",
        "ml.prediction",
        ("prediction", "predicted", "score", "probability", "logit"),
        references=(DQV,),
    ),
)

CONCEPT_BY_ID = {concept.id: concept for concept in REFERENCE_CONCEPTS}


__all__ = [
    "CENSUS_GEOCODER",
    "CONCEPT_BY_ID",
    "DQV",
    "E164",
    "GLEIF",
    "REFERENCE_CONCEPTS",
    "RFC5322",
    "SCHEMA_ORG",
    "SHACL",
    "USPS_PUB28",
]
